"""Run every test sequentially and keep fresh evidence out of accepted reports."""
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import time
from urllib.parse import parse_qs, urlsplit
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]


def test_database_is_isolated(dsn):
    try:
        parts = urlsplit(dsn)
        return (parts.scheme in ("postgres", "postgresql")
                and re.fullmatch(r"/nfc_v12_test(?:_[a-z0-9]+)?", parts.path) is not None and not parts.fragment
                and not {"dbname", "database", "service"}.intersection(parse_qs(parts.query)))
    except ValueError:
        return False


def main():
    os.chdir(ROOT)
    if not test_database_is_isolated(os.environ.get("NFC_TEST_DATABASE_URL", "")):
        raise SystemExit("Set NFC_TEST_DATABASE_URL to isolated nfc_v12_test or nfc_v12_test_<suffix>")
    os.environ.setdefault("NFC_BROWSER_EVIDENCE", str(ROOT / "work/qa/v12"))
    os.environ.setdefault("NFC_V13_BROWSER_EVIDENCE", str(ROOT / "work/qa/v13"))
    os.environ["NFC_TELEGRAM_ENABLED"] = "false"
    os.environ["PYTHONDONTWRITEBYTECODE"] = "1"
    evidence = ROOT / "work/test-run"
    evidence.mkdir(parents=True, exist_ok=True)
    summary = {"complete": False, "browser_only": "--browser-only" in sys.argv, "groups": []}

    def save():
        (evidence / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    def run(label, args, report=None):
        start = time.monotonic()
        result = subprocess.run(args, check=False)
        row = {"group": label, "exit_code": result.returncode, "seconds": round(time.monotonic() - start, 2)}
        if report and report.exists():
            suites = ET.parse(report).getroot()
            row.update({field: sum(int(s.get(field, "0")) for s in suites.iter("testsuite"))
                        for field in ("tests", "failures", "errors", "skipped")})
        summary["groups"].append(row)
        save()
        if result.returncode:
            raise SystemExit(result.returncode)
        if report and (not report.exists() or row.get("skipped") or not row.get("tests")):
            raise SystemExit("Test group lacks complete, unskipped evidence")

    def pytest(label, selectors):
        report = evidence / (label + ".xml")
        if report.exists():
            report.unlink()  # Only the exact old report generated by this runner.
        run(label, [sys.executable, "-B", "-m", "pytest", "-q", "-p", "no:cacheprovider",
                    "--junitxml=" + str(report), *selectors], report)

    save()
    run("build-for-tests", ["node", "src/build.mjs"])
    if not summary["browser_only"]:
        pytest("unit-integration", ["tests", "--ignore=tests/test_v12_browser.py", "--ignore=tests/test_v13_browser.py"])
    for width in [320, 360, 390, 430, 768, 1024, 1280, 1440]:
        pytest(f"browser-width-{width}", [f"tests/test_v12_browser.py::test_eight_width_bilingual_route_and_screenshot_matrix[{width}]"])
    pytest("browser-v12-flows", ["tests/test_v12_browser.py", "-k", "not eight_width"])
    pytest("browser-v13", ["tests/test_v13_browser.py"])
    summary["complete"] = True
    save()
    print("Complete sequential test run:", sum(g.get("tests", 0) for g in summary["groups"]), "checks; no skipped groups")


if __name__ == "__main__":
    main()
