(()=>{
'use strict';
const basePath=document.documentElement.dataset.publicBasePath||'',pages=document.documentElement.dataset.deploymentTarget==='github-pages';
const locale=document.documentElement.lang,uk=locale==='uk',P=(a,b)=>uk?a:b,local=p=>basePath+(uk?'':'/en')+p;
const safeSession={get:k=>{try{return sessionStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{sessionStorage.setItem(k,v);return true}catch{return false}},remove:k=>{try{sessionStorage.removeItem(k)}catch{}}};
const menu=document.querySelector('#mobile-menu'),trigger=document.querySelector('.menu-toggle');let scrollBefore=0;
 function closeMenu(){if(!menu.open)return;menu.close();document.body.style.position='';document.body.style.top='';document.body.style.width='';window.scrollTo({top:scrollBefore,behavior:'instant'});trigger.setAttribute('aria-expanded','false');trigger.focus({preventScroll:true});}
 trigger?.addEventListener('click',()=>{scrollBefore=scrollY;document.body.style.position='fixed';document.body.style.top=`-${scrollBefore}px`;document.body.style.width='100%';menu.showModal();trigger.setAttribute('aria-expanded','true');menu.querySelector('button').focus();});
 menu?.querySelector('.menu-close').addEventListener('click',closeMenu);menu?.addEventListener('cancel',e=>{e.preventDefault();closeMenu()});menu?.addEventListener('click',e=>{if(e.target===menu)closeMenu();if(e.target.closest('a'))closeMenu()});window.addEventListener('resize',()=>{if(innerWidth>1350)closeMenu()});
 menu?.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...menu.querySelectorAll('a[href],button:not([disabled])')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||!menu.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!menu.contains(document.activeElement))){e.preventDefault();first.focus();}});
const params=new URLSearchParams(location.search);
function hashFocus(){let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}const el=document.getElementById(id);if(!el)return;if(el.tagName==='DETAILS')el.open=true;document.fonts.ready.then(()=>requestAnimationFrame(()=>{el.scrollIntoView({block:'start',behavior:'instant'});if(el.tabIndex===-1)el.focus({preventScroll:true})}));}
hashFocus();window.addEventListener('hashchange',hashFocus);
const thumbs=[...document.querySelectorAll('[data-gallery]')];
thumbs.forEach((button,index)=>{
 button.onclick=()=>{
  thumbs.forEach((b,i)=>{b.setAttribute('aria-pressed',String(i===index));document.getElementById('gallery-'+i).hidden=i!==index;});
  document.querySelector('.gallery-position').textContent=`${index+1} / ${thumbs.length}`;
  const figure=document.getElementById('gallery-'+index),header=document.querySelector('.header');if(figure.getBoundingClientRect().top<(header?.offsetHeight||0)+16)figure.scrollIntoView({block:'start',behavior:'instant'});
  window.dispatchEvent(new CustomEvent('nfc:gallery',{detail:{image_index:index}}));
 };
 button.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?thumbs.length-1:(index+(e.key==='ArrowRight'?1:-1)+thumbs.length)%thumbs.length;thumbs[n].click();thumbs[n].focus({preventScroll:true});}};
});
const story=document.querySelector('#founder-story');
if(story){
 const videos=[...story.querySelectorAll('video')],toggle=story.querySelector('.story-toggle'),motion=matchMedia('(prefers-reduced-motion: reduce)');let visible=false,userPaused=false;
 function update(){
  toggle.hidden=motion.matches;toggle.setAttribute('aria-pressed',String(userPaused));toggle.textContent=userPaused?P('Відтворити фон','Play background'):P('Призупинити фон','Pause background');
  for(const video of videos){
   if(motion.matches||!visible||userPaused||document.hidden){video.pause();if(motion.matches)video.dataset.playing='false';continue;}
   if(!video.src){video.autoplay=true;video.src=video.dataset.source;video.load();}
   video.play().then(()=>{if(!motion.matches&&visible&&!userPaused&&!document.hidden)video.dataset.playing='true';else video.pause();}).catch(()=>{video.dataset.playing='false';});
  }
 }
 toggle.onclick=()=>{userPaused=!userPaused;update();};
 motion.addEventListener('change',update);document.addEventListener('visibilitychange',update);
 new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;update();},{threshold:.05}).observe(story);update();
}
const store={async act(kind,value){const db=await new Promise((yes,no)=>{const r=indexedDB.open('nfc-v6-request-drafts',1);r.onupgradeneeded=()=>r.result.createObjectStore('pending');r.onsuccess=()=>yes(r.result);r.onerror=()=>no(r.error)});try{return await new Promise((yes,no)=>{const tx=db.transaction('pending',kind==='get'?'readonly':'readwrite'),s=tx.objectStore('pending'),r=kind==='get'?s.get('request'):kind==='delete'?s.delete('request'):s.put(value,'request');let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>yes(result);tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error)})}finally{db.close()}}};
const phone=v=>/^\+?[\d ()-]+$/.test(v)&&v.replace(/\D/g,'').length>=7&&v.replace(/\D/g,'').length<=15;
function maps(v){try{const u=new URL(v),h=u.hostname;if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443')return false;if(['maps.app.goo.gl','g.page'].includes(h))return u.pathname.length>1;if(h==='goo.gl')return u.pathname.startsWith('/maps/')&&u.pathname.length>6;if(['maps.google.com','maps.google.com.ua','maps.google.co.uk'].includes(h))return true;return ['google.com','www.google.com','google.com.ua','www.google.com.ua','google.co.uk','www.google.co.uk'].includes(h)&&(u.pathname==='/maps'||u.pathname.startsWith('/maps/'))}catch{return false}}
function businessURL(v){try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password&&u.hostname.includes('.')&&!['localhost','127.0.0.1'].includes(u.hostname)}catch{return false}}
function reveal(el){el.hidden=false;requestAnimationFrame(()=>{el.scrollIntoView({block:'center',behavior:'instant'});el.focus({preventScroll:true})})}
window.nfcAnalyticsEvents=[];
async function start(){let c;try{const r=await fetch(basePath+'/assets/content.json');if(!r.ok)throw Error();c=await r.json()}catch{return}
const T=x=>x?.[locale],U=(k,a,b)=>T(c.ui[k])||P(a,b),commerce=c.commerce,interests=commerce.interests,quantities=commerce.quantities;
const quote=(v,q)=>!interests.includes(v)?{status:'choose'}:({status:q==='more'||commerce.customQuoteInterests.includes(v)?'custom':'fixed',amount:q==='more'||commerce.customQuoteInterests.includes(v)?null:commerce.variants[v]?.prices[q],currency:'UAH',deposit:200,depositIncluded:true});
const price=q=>q?.status==='choose'?P('Оберіть варіант для розрахунку','Choose a variant to see the price'):q?.status==='custom'?P('Індивідуальний розрахунок','Individual quote'):(uk?'':'UAH ')+new Intl.NumberFormat(uk?'uk-UA':'en-GB').format(q?.amount||0)+(uk?' грн':'');
const names=new Set(c.events);function event(name,d={}){if(pages&&document.documentElement.dataset.publicationMode==='PUBLIC_PREVIEW')return;if(!names.has(name))return;const item={event:name,locale,route:document.body.dataset.route};if(interests.includes(d.variant))item.variant=d.variant;if(quantities.includes(String(d.quantity)))item.quantity=String(d.quantity);if(Number.isInteger(d.image_index)&&d.image_index>=0&&d.image_index<6)item.image_index=d.image_index;window.nfcAnalyticsEvents.push(item);if(window.nfcAnalyticsEvents.length>100)window.nfcAnalyticsEvents.shift();window.dispatchEvent(new CustomEvent('nfc:analytics',{detail:item}))}
document.querySelectorAll('[data-event]').forEach(a=>{if(c.commerceEvents?.includes(a.dataset.event))return;a.addEventListener('click',()=>{if(a.dataset.event==='order_start'){safeSession.set('nfc-v6-source',location.pathname);if(!a.dataset.variant)safeSession.set('nfc-v6-reset','yes')}event(a.dataset.event,a.dataset)});});
document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)event('faq_open')}));document.querySelectorAll('.story-section video').forEach(v=>v.addEventListener('play',()=>event('founder_story_video_play')));
if(document.querySelector('.product-rows'))event('catalog_view');
window.addEventListener('nfc:gallery',e=>event('product_gallery_view',e.detail));if(thumbs.length)event('product_gallery_view',{image_index:0});
if(story){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){event('founder_story_view');observer.disconnect();}},{threshold:.15});observer.observe(story);}
if(!pages&&!safeSession.get('nfc-v6-attribution')){const a={};for(const[k,v]of params)if(/^utm_(source|medium|campaign|content|term)$/.test(k)&&v.length<=200)a[k]=v;try{if(document.referrer){const u=new URL(document.referrer);if(['http:','https:'].includes(u.protocol))a.referrer=u.origin+u.pathname}}catch{}safeSession.set('nfc-v6-attribution',JSON.stringify(a));safeSession.set('nfc-v6-source',location.pathname)}
let selection={variant:'standard',quantity:'1'};try{selection={...selection,...JSON.parse(safeSession.get('nfc-v6-selection')||'{}')}}catch{}if(['standard','branded'].includes(params.get('variant')))selection.variant=params.get('variant');if(quantities.includes(params.get('quantity')))selection.quantity=params.get('quantity');
const pdp=document.querySelector('.product-order');if(pdp){const radios=[...pdp.querySelectorAll('[name=variant]')];for(const r of radios)r.checked=r.value===selection.variant;pdp.elements.quantity.value=selection.quantity;
function sync(){selection={variant:radios.find(r=>r.checked)?.value||'standard',quantity:pdp.elements.quantity.value};safeSession.set('nfc-v6-selection',JSON.stringify(selection));const v=c.variants.find(v=>v.id===selection.variant);document.querySelector('[data-product-price]').textContent=price(quote(selection.variant,selection.quantity));document.querySelector('[data-product-cta]').textContent=selection.quantity==='more'?P('Розрахувати замовлення','Request a quote'):T(v.cta);document.querySelector('[data-variant-description]').textContent=T(v.description);const a=document.querySelector('.sticky-order .button');a.href=local('/order')+`?variant=${selection.variant}&quantity=${selection.quantity}`;a.textContent=document.querySelector('[data-product-cta]').textContent;Object.assign(a.dataset,selection);document.querySelector('[data-variant-title]').textContent=v.name;document.querySelector('[data-branded-note]').hidden=selection.variant!=='branded';for(const el of document.querySelectorAll('[data-package-prices] [data-quantity-price]'))el.textContent=price(quote(selection.variant,el.dataset.quantityPrice));const f=document.querySelector('.lead-form');if(f?.dataset.enhanced){f.elements.variant.value=selection.variant;f.elements.quantity.value=selection.quantity;f.dispatchEvent(new Event('nfc:selection'))}}
sync();for(const r of radios)r.onchange=()=>{sync();event('product_variant_select',selection)};pdp.elements.quantity.onchange=()=>{sync();event('quantity_select',selection)};pdp.onsubmit=()=>{safeSession.set('nfc-v6-source',location.pathname);event('order_start',selection)};event('product_details_open',selection)}
document.querySelectorAll('.locale-switch').forEach(a=>a.addEventListener('click',()=>{const u=new URL(a.href);const form=document.querySelector('.lead-form');const values=pdp?selection:form?{variant:form.elements.variant.value,quantity:form.elements.quantity.value}:Object.fromEntries(params);for(const k of ['variant','quantity'])if(values[k])u.searchParams.set(k,values[k]);u.hash=location.hash;a.href=u.href}));
if(pages)return;
/* NFC_FULLSTACK_START */
function project(r){if(!r||!/^NFC-[A-F0-9]{20}$/.test(r.id||'')||!interests.includes(r.variant)||!quantities.includes(r.quantity)||!r.quote||!['fixed','confirmed','custom'].includes(r.quote.status)||r.quote.currency!=='UAH'||!['local_test','live','saved'].includes(r.mode)||typeof r.quote.pricingRevision!=='string'||(r.quote.status==='custom'?r.quote.amount!==null:!Number.isSafeInteger(r.quote.amount)||r.quote.amount<=0))throw Error('invalid_receipt');return{id:r.id,variant:r.variant,quantity:r.quantity,quote:{status:r.quote.status,amount:r.quote.amount,currency:'UAH',deposit:200,depositIncluded:true,pricingRevision:r.quote.pricingRevision},mode:r.mode}}
function receiptView(el,r){el.replaceChildren();const h=document.createElement('h2'),p=document.createElement('p'),dl=document.createElement('dl');h.textContent=r.mode==='local_test'?U('localSuccess','Тестову заявку збережено','Test request saved'):U('success','Дякуємо! Вашу заявку отримано.','Thank you! Your request has been received.');p.textContent=r.mode==='local_test'?P('Заявку збережено локально. Повідомлення в Telegram та email не надсилалися.','The request was saved locally. No Telegram or email messages were sent.'):U('successText','Ми зв’яжемося з вами в обраному месенджері.','We’ll contact you in your selected messenger.');for(const[label,value]of [[P('Номер заявки','Request number'),r.id],[P('Варіант','Variant'),c.variants.find(v=>v.id===r.variant)?.name||P('Індивідуальний запит','Individual request')],[P('Кількість','Quantity'),r.quantity==='more'?P('Більше 2','More than 2'):r.quantity],[P('Вартість','Price'),price(r.quote)]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dl.append(dt,dd)}el.append(h,p,dl);if(r.variant==='branded'){const p=document.createElement('p');p.textContent=r.mode==='live'?U('brandedSuccess','Переглянемо сторінку бізнесу та підготуємо перший макет безкоштовно.','We will review your business page and prepare the first mockup for free.'):P('Перший макет безкоштовний і не зобов’язує до замовлення.','The first mockup is free, with no obligation to order.');el.append(p)}el.dataset.status='success'}
const receiptEl=document.querySelector('#receipt');if(receiptEl){try{const r=JSON.parse(safeSession.get('nfc-v6-receipt')||'null');if(r)receiptView(receiptEl,project(r))}catch{}}
const form=document.querySelector('.lead-form');if(!form||form.hasAttribute('data-commerce-form'))return;const q=n=>form.elements.namedItem(n),key='nfc-v6-draft';let busy=false,token=null,fingerprint=null,draft={};try{draft=JSON.parse(safeSession.get(key)||'{}')}catch{}let pending;try{pending=await store.act('get')}catch{}if(pending?.payload?.contractVersion===6&&!pending.committed){draft={...draft,...pending.payload};token=pending.payload.requestToken;fingerprint=pending.fingerprint}
for(const[n,v]of Object.entries(draft)){const el=q(n);if(el&&!['hidden','submit'].includes(el.type)&&n!=='consent'){if(el.type==='checkbox')el.checked=!!v;else el.value=v}}
if(form.dataset.variant)q('variant').value=form.dataset.variant;if(interests.includes(params.get('variant')))q('variant').value=params.get('variant');if(quantities.includes(params.get('quantity')))q('quantity').value=params.get('quantity');if(pdp){q('variant').value=selection.variant;q('quantity').value=selection.quantity}if(!interests.includes(q('variant').value))q('variant').value='';if(!quantities.includes(q('quantity').value))q('quantity').value='1';if(safeSession.get('nfc-v6-reset')==='yes'){q('variant').value='';q('quantity').value='1';safeSession.remove('nfc-v6-reset')}token=token||draft._token;fingerprint=fingerprint||draft._fingerprint;
let legacy=!!(safeSession.get('nfc-draft-order')||safeSession.get('nfc-draft-contact'));try{legacy=legacy||(await indexedDB.databases()).some(d=>d.name==='nfc-test-request-drafts')}catch{}if(legacy){const el=form.querySelector('.legacy-notice');el.textContent=P('У браузері є чернетка попередньої версії. Вона збережена окремо та не переноситься автоматично. Перевірте статус попередньої заявки перед новою спробою.','This browser has a draft from the previous version. It is preserved separately and is not transferred automatically. Check the previous request status before trying again.');el.hidden=false}
function data(){const out={contractVersion:6};for(const n of ['name','phone','messenger','messengerContact','variant','quantity','business','maps','businessUrl','comment','website'])out[n]=String(q(n)?.value||'').trim();out.differentContact=q('differentContact').checked;out.consent=q('consent').checked;if(!out.differentContact)out.messengerContact='';if(out.variant!=='branded')out.businessUrl='';out.locale=pending?.payload?.locale||locale;out.source=pending?.payload?.source||(document.body.dataset.route==='/order'?(params.has('source')?q('source').value:(safeSession.get('nfc-v6-source')||q('source').value||location.pathname)):location.pathname);out.displayed_price=price(quote(out.variant,out.quantity));try{out.attribution=pending?.payload?.attribution||JSON.parse(safeSession.get('nfc-v6-attribution')||'{}')}catch{out.attribution={}}return out}
function save(){const out=data();delete out.consent;out._token=token;out._fingerprint=fingerprint;safeSession.set(key,JSON.stringify(out))}
function conditional(announce=false){if(pending?.payload){pendingLock();return}const branded=q('variant').value==='branded',different=q('differentContact').checked,bulk=q('variant').value==='bulk';if(bulk)q('quantity').value='more';for(const[sel,n,show]of [['.conditional-business','businessUrl',branded],['.conditional-contact','messengerContact',different]]){form.querySelector(sel).hidden=!show;q(n).disabled=!show;q(n).required=show}for(const o of q('quantity').options)o.disabled=bulk&&o.value!=='more';form.querySelector('[data-form-price]').textContent=price(quote(q('variant').value,q('quantity').value));q('displayed_price').value=form.querySelector('[data-form-price]').textContent;if(announce)form.querySelector('.conditional-announcement').textContent=[branded?P('Для брендованого макета додайте посилання на бізнес.','Add a business page link for the branded mockup.'):'',different?P('Вкажіть інший контакт: Telegram username або номер; WhatsApp / Viber — номер телефону.','Enter another contact: Telegram username or phone; WhatsApp / Viber — phone number.'):''].filter(Boolean).join(' ');save()}
conditional();form.addEventListener('nfc:selection',()=>conditional(true));q('variant').onchange=()=>{conditional(true);event('product_variant_select',data())};q('quantity').onchange=()=>{conditional();event('quantity_select',data())};q('differentContact').onchange=q('messenger').onchange=()=>conditional(true);form.addEventListener('input',save);
function clear(){form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));form.querySelectorAll('.field-error').forEach(el=>{el.hidden=true;el.textContent=''});form.querySelector('.error-summary').hidden=true}
function errors(list){clear();const summary=form.querySelector('.error-summary'),h=document.createElement('strong'),ul=document.createElement('ul');h.textContent=P('Перевірте дані у формі','Check the form details');summary.replaceChildren(h);for(const n of [...new Set(list)]){const el=q(n),message=T(c.errors[n])||U('errorText','Перевірте це поле.','Check this field.'),p=form.querySelector('#e-'+n);if(p){p.hidden=false;p.textContent=message}if(el){el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',(n==='maps'?'maps-hint ':'')+'e-'+n);const li=document.createElement('li'),a=document.createElement('a');a.href='#f-'+n;a.textContent=message;a.onclick=e=>{e.preventDefault();el.scrollIntoView({block:'center',behavior:'instant'});el.focus({preventScroll:true})};li.append(a);ul.append(li)}}summary.append(ul);reveal(summary)}
function validate(o){const bad=[];if(!o.name||o.name.length>120)bad.push('name');if(!phone(o.phone))bad.push('phone');if(!['telegram','whatsapp','viber'].includes(o.messenger))bad.push('messenger');if(o.differentContact&&!(o.messenger==='telegram'?(phone(o.messengerContact)||/^@[A-Za-z][A-Za-z0-9_]{4,31}$/.test(o.messengerContact)||/^https:\/\/t\.me\/[A-Za-z][A-Za-z0-9_]{4,31}$/.test(o.messengerContact)):phone(o.messengerContact)))bad.push('messengerContact');if(!interests.includes(o.variant))bad.push('variant');if(!quantities.includes(o.quantity)||o.variant==='bulk'&&o.quantity!=='more')bad.push('quantity');if(o.maps&&!maps(o.maps))bad.push('maps');if(o.variant==='branded'&&!businessURL(o.businessUrl))bad.push('businessUrl');if(!o.consent)bad.push('consent');return bad}
function pendingLock(){const locked=!!pending?.payload;if(locked)for(const[n,v]of Object.entries(pending.payload)){const el=q(n);if(el&&!['hidden','submit'].includes(el.type)){if(el.type==='checkbox')el.checked=!!v;else el.value=v}}for(const el of form.elements)if(!['hidden','submit','button'].includes(el.type))el.disabled=locked;if(locked){form.querySelector('[data-form-price]').textContent=price(quote(pending.payload.variant,pending.payload.quantity));q('displayed_price').value=pending.payload.displayed_price||'';}const note=form.querySelector('.pending-notice');note.hidden=!locked;if(locked)note.textContent=P('Результат попередньої спроби ще не підтверджено. Повторимо ту саму заявку з тими самими даними, щоб не створити дублікат.','The previous attempt is not confirmed yet. We will retry the same request with the same details to avoid a duplicate.');else conditional()}pendingLock();form.noValidate=true;form.onsubmit=async e=>{e.preventDefault();if(busy)return;const out=pending?.payload?{...pending.payload}:data(),bad=validate(out);if(bad.length){errors(bad);event('order_submit_error');return}clear();busy=true;const button=form.querySelector('.submit-button'),label=button.textContent,result=form.querySelector('.form-result');button.disabled=true;button.textContent=U('submitting','Надсилаємо…','Sending…');form.setAttribute('aria-busy','true');result.hidden=true;event('order_start',out);
try{delete out.requestToken;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(out))),next=Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');if(next!==fingerprint||!token){token=crypto.randomUUID();fingerprint=next}out.requestToken=token;save();pending={payload:out,fingerprint};pendingLock();await store.act('put',pending);const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(out),signal:AbortSignal.timeout(20000)}),value=await response.json();if(!response.ok||value.ok!==true){if(value.errors){pending=null;await store.act('delete');pendingLock();errors(Array.isArray(value.errors)?value.errors:Object.keys(value.errors));event('order_submit_error');return}throw Error(value.code||'request_failed')}
const r=project(value.receipt);pending=null;receiptView(result,r);form.dataset.complete='true';reveal(result);safeSession.remove(key);try{await store.act('put',{committed:true,receipt:r});await store.act('delete')}catch{}event('order_submit_success',r);const stored=safeSession.set('nfc-v6-receipt',JSON.stringify(r)),a=document.querySelector('.sticky-order .button');a.href=local('/solutions');a.textContent=P('До карток','Back to cards');if(stored)location.assign(local('/thank-you'));else{const a=document.createElement('a');a.href=local('/solutions');a.className='button';a.textContent=P('До карток','Back to cards');result.append(a)}
}catch(error){result.replaceChildren();const h=document.createElement('h2'),p=document.createElement('p'),retry=document.createElement('button');h.textContent=U('error','Не вдалося надіслати заявку','The request could not be sent');p.textContent=error.message==='rate_limited'?P('Забагато спроб. Зачекайте хвилину. Дані залишилися у формі.','Too many attempts. Wait a minute. Your details remain in the form.'):U('errorText','Спробуйте ще раз або напишіть у Telegram.','Try again or contact us on Telegram.');retry.type='button';retry.className='button secondary';retry.textContent=U('retry','Спробувати ще раз','Try again');retry.onclick=()=>form.requestSubmit();result.append(h,p,retry);result.dataset.status='error';reveal(result);event('order_submit_error')}finally{busy=false;button.disabled=false;button.textContent=label;form.removeAttribute('aria-busy')}};
const context=document.modelContext;if(context?.registerTool){const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'configure_nfc_request',title:'Prepare an NFC CARD request',description:'Set a variant and quantity in the visible form. Does not send a request.',inputSchema:{type:'object',properties:{variant:{type:'string',enum:interests},quantity:{type:'string',enum:quantities}},required:['variant','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!interests.includes(input?.variant)||!quantities.includes(input?.quantity)||input.variant==='bulk'&&input.quantity!=='more')throw Error('Invalid configuration');q('variant').value=input.variant;q('quantity').value=input.quantity;conditional(true);return{variant:q('variant').value,quantity:q('quantity').value,submitted:false}}},{signal:controller.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
form.dataset.enhanced='true';
/* NFC_FULLSTACK_END */
}
start();
})();
