/* Commerce interactions. Canonical amounts are shared data; the server validates every order. */
(()=>{'use strict';
const basePath=document.documentElement.dataset.publicBasePath||'',pages=document.documentElement.dataset.deploymentTarget==='github-pages';
const uk=document.documentElement.lang==='uk',P=(a,b)=>uk?a:b,locale=uk?'uk':'en',params=new URLSearchParams(location.search);
const safe={get(k){try{return sessionStorage.getItem(k)}catch{return null}},set(k,v){try{sessionStorage.setItem(k,v)}catch{}},remove(k){try{sessionStorage.removeItem(k)}catch{}}};
const allowedEvents=new Set(["catalog_product_open", "product_row_click", "product_variant_select", "product_gallery_view", "product_gallery_slide", "product_details_open", "product_details_expand", "product_cross_sell_click", "sticky_order_cta_view", "sticky_order_cta_click", "messenger_preference_select", "quantity_select", "order_start", "order_submit_success", "order_submit_error"]);
function event(name,data={}){if(pages&&document.documentElement.dataset.publicationMode==='PUBLIC_PREVIEW')return;if(!allowedEvents.has(name))return;const value={event:name,locale,route:document.body.dataset.route};if(['standard','branded','bulk','consultation'].includes(data.variant))value.variant=data.variant;if(['1','2','more'].includes(data.quantity))value.quantity=data.quantity;if(['telegram','whatsapp','viber'].includes(data.messenger))value.messenger=data.messenger;if(Number.isInteger(data.asset_index)&&data.asset_index>=0&&data.asset_index<5)value.asset_index=data.asset_index;window.nfcAnalyticsEvents??=[];window.nfcAnalyticsEvents.push(value);if(window.nfcAnalyticsEvents.length>100)window.nfcAnalyticsEvents.shift();window.dispatchEvent(new CustomEvent('nfc:analytics',{detail:value}));}
document.querySelectorAll('[data-event]').forEach(el=>{if(allowedEvents.has(el.dataset.event))el.addEventListener('click',()=>{event(el.dataset.event,el.dataset);if(el.dataset.event==='catalog_product_open')event('product_row_click',el.dataset);});});
const gallery=document.querySelector('[data-commerce-gallery]');
if(gallery)window.NFCGallery.mount(gallery,event);
const disclosure=document.querySelector('#product-details');disclosure?.addEventListener('toggle',()=>{const summary=disclosure.querySelector('summary');summary.textContent=disclosure.open?P('Згорнути деталі','Collapse details'):document.querySelector('[data-product]')?.dataset.product==='branded'?P('Детальніше про брендовану картку','More about the branded card'):P('Детальніше про картку','More about the card');if(disclosure.open){event('product_details_expand');}});
const pendingStore={key:'general',async act(action,value){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('nfc-commerce-v11',1);r.onupgradeneeded=()=>r.result.createObjectStore('pending');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise((resolve,reject)=>{const tx=db.transaction('pending',action==='get'?'readonly':'readwrite'),store=tx.objectStore('pending'),r=action==='get'?store.get('order:'+this.key):action==='delete'?store.delete('order:'+this.key):store.put(value,'order:'+this.key);let output;r.onsuccess=()=>output=r.result;tx.oncomplete=()=>resolve(output);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}};
async function boot(){
 const response=await fetch(basePath+'/assets/content.json');if(!response.ok)return;const content=await response.json(),commerce=content.commerce,validQ=q=>commerce.quantities.includes(q),validV=v=>commerce.interests.includes(v);
 const quote=(v,q)=>!validV(v)||q==='more'||commerce.customQuoteInterests.includes(v)?{status:'custom',amount:null}:{status:'fixed',amount:commerce.variants[v]?.prices[q]};
 const price=(v,q)=>quote(v,q).status==='custom'?P('Індивідуальний розрахунок','Custom quote'):(uk?'':'UAH ')+new Intl.NumberFormat(uk?'uk-UA':'en-GB').format(quote(v,q).amount)+(uk?' грн':'');
 const product=document.querySelector('[data-product]'),form=document.querySelector('[data-commerce-form]'),topQuantity=document.querySelector('#purchase-quantity'),sticky=document.querySelector('[data-commerce-sticky]');
 let selected={variant:product?.dataset.product||form?.dataset.variant||'consultation',quantity:validQ(params.get('quantity'))?params.get('quantity'):'1'},pending=null,busy=false,topSeen=false;
 if(!product&&validV(params.get('variant')))selected.variant=params.get('variant');
 let attribution={};try{if(!pages)attribution=JSON.parse(safe.get('nfc-v6-attribution')||'{}')}catch{}for(const [k,v]of params)if(/^utm_(source|medium|campaign|content|term)$/.test(k)&&v.length<=200)attribution[k]=v;
 function setLinks(){document.querySelectorAll('a[href]').forEach(a=>{const u=new URL(a.href,location.origin);if(u.origin!==location.origin)return;if(!/(\/solutions\/(?:branded-)?review-card|\/order)\/?$/.test(u.pathname))return;for(const[k,v]of Object.entries(attribution))if(/^utm_/.test(k))u.searchParams.set(k,v);if(/\/order\/?$/.test(u.pathname))u.searchParams.set('source',location.pathname);a.href=u.pathname+u.search+u.hash;});}
 function sync(){if(selected.variant==='bulk')selected.quantity='more';if(topQuantity)topQuantity.value=selected.quantity;if(form){form.elements.variant.value=selected.variant;form.elements.quantity.value=selected.quantity;form.elements.displayed_price.value=price(selected.variant,selected.quantity);const output=form.querySelector('[data-form-price]');if(output)output.textContent=price(selected.variant,selected.quantity);}
 document.querySelectorAll('[data-current-price],[data-sticky-price]').forEach(el=>el.textContent=price(selected.variant,selected.quantity));const u=new URL(location.href);if(product){u.searchParams.set('quantity',selected.quantity);u.searchParams.delete('variant');history.replaceState(null,'',u.pathname+u.search+u.hash);}safe.set('nfc-v11-selection',JSON.stringify(selected));}
 if(form){const preset=validV(params.get('variant'));if(!product&&preset){const control=form.elements.variant;const wrapper=control.closest('.field');if(wrapper){const hidden=document.createElement('input');hidden.type='hidden';hidden.name='variant';hidden.value=selected.variant;wrapper.replaceWith(hidden);}}form.elements.variant.value=selected.variant;form.elements.quantity.value=selected.quantity;}
 sync();setLinks();if(product){event('product_details_open',selected);event('product_gallery_view',{asset_index:0});}
 if(topQuantity)topQuantity.onchange=()=>{if(pending)return;selected.quantity=topQuantity.value;sync();event('quantity_select',selected);};
 document.querySelectorAll('[data-order-entry]').forEach(a=>a.addEventListener('click',()=>{sync();safe.set('nfc-v6-source',location.pathname);event(a.hasAttribute('data-sticky-order')?'sticky_order_cta_click':'order_start',selected);}));
 document.querySelectorAll('.locale-switch').forEach(a=>a.addEventListener('click',()=>{const u=new URL(a.href);u.searchParams.delete('variant');if(product||form){u.searchParams.set('quantity',selected.quantity);if(!product)u.searchParams.set('variant',selected.variant);}for(const[k,v]of Object.entries(attribution))if(/^utm_/.test(k))u.searchParams.set(k,v);u.hash=location.hash;a.href=u.pathname+u.search+u.hash;}));
 if(sticky){const top=document.querySelector('[data-top-order]');function visibility(){const rect=top.getBoundingClientRect(),formRect=form.getBoundingClientRect(),focused=form.contains(document.activeElement),atForm=formRect.top<innerHeight&&formRect.bottom>0;const show=innerWidth<=768&&rect.bottom<0&&!focused&&!atForm&&!form.dataset.complete;if(show&&!topSeen){event('sticky_order_cta_view',selected);topSeen=true;}sticky.hidden=!show;}new IntersectionObserver(visibility).observe(top);new IntersectionObserver(visibility).observe(form);window.addEventListener('scroll',visibility,{passive:true});window.addEventListener('resize',visibility);document.addEventListener('focusin',visibility);document.addEventListener('focusout',()=>requestAnimationFrame(visibility));visibility();}
 if(!form)return;
 if(pages){
  const {mountPagesForm}=await import(basePath+'/assets/pages.mjs');
  mountPagesForm(form,{endpoint:document.documentElement.dataset.leadEndpoint||'',basePath,locale,pathname:location.pathname,attribution,
   selection:()=>selected,select:value=>{selected=value;sync();},lockSelection:locked=>{pending=locked?{}:null;if(topQuantity)topQuantity.disabled=locked;},event});
  return;
 }
 /* NFC_FULLSTACK_START */
 pendingStore.key=product?.dataset.product||(validV(params.get('variant'))?params.get('variant'):'general');
 const q=n=>form.elements.namedItem(n),draftKey='nfc-v11-draft:'+location.pathname;let token=q('requestToken').value||crypto.randomUUID();
 try{const draft=JSON.parse(safe.get(draftKey)||'{}');for(const name of ['name','phone','messenger','comment'])if(draft[name])q(name).value=draft[name];pending=await pendingStore.act('get');}catch{}
 function data(){return {contractVersion:6,name:q('name').value.trim(),phone:q('phone').value.trim(),messenger:q('messenger').value,variant:selected.variant,quantity:selected.quantity,comment:q('comment').value.trim(),consent:q('consent').checked,website:q('website').value,locale,source:q('source').value||location.pathname,attribution,displayed_price:price(selected.variant,selected.quantity)};}
 function lock(){if(!pending)return;const o=pending.payload;for(const name of ['name','phone','messenger','comment'])q(name).value=o[name];q('consent').checked=o.consent;selected={variant:o.variant,quantity:o.quantity};sync();for(const el of form.elements)if(!['hidden','submit','button'].includes(el.type))el.disabled=true;if(topQuantity)topQuantity.disabled=true;const note=form.querySelector('.pending-notice');note.hidden=false;note.textContent=P('Попередню спробу ще не підтверджено. Повторимо ту саму заявку, щоб не створити дублікат.','The previous attempt is not confirmed. We will retry the same request to avoid a duplicate.');}
 function unlock(){for(const el of form.elements)el.disabled=false;if(topQuantity)topQuantity.disabled=false;form.querySelector('.pending-notice').hidden=true;}
 lock();
 form.addEventListener('input',()=>{if(pending)return;const d=data();safe.set(draftKey,JSON.stringify({name:d.name,phone:d.phone,messenger:d.messenger,comment:d.comment}));});
 form.addEventListener('change',e=>{if(pending)return;if(e.target.name==='variant'||e.target.name==='quantity'){selected={variant:q('variant').value,quantity:q('quantity').value};sync();event(e.target.name==='variant'?'product_variant_select':'quantity_select',selected);}if(e.target.name==='messenger'){if(e.target.checked&&['telegram','whatsapp','viber'].includes(e.target.value)){const message=form.querySelector('#e-messenger');message.hidden=true;message.textContent='';for(const radio of form.querySelectorAll('[name=messenger]')){radio.removeAttribute('aria-invalid');if(radio.getAttribute('aria-describedby')==='e-messenger')radio.removeAttribute('aria-describedby');}if(!form.querySelector('[aria-invalid=true]'))form.querySelector('.error-summary').hidden=true;}event('messenger_preference_select',{messenger:e.target.value});}});
 const messages={name:P('Вкажіть ім’я.','Enter your name.'),phone:P('Вкажіть номер телефону.','Enter a valid phone number.'),messenger:P('Оберіть зручний месенджер.','Choose a messenger.'),quantity:P('Оберіть кількість.','Choose a quantity.'),consent:P('Потрібна згода на обробку даних.','Consent is required.'),comment:P('Коментар має бути до 2000 символів.','Keep your comment within 2000 characters.')};
 function clear(){form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));form.querySelectorAll('.field-error').forEach(el=>{el.hidden=true;el.textContent=''});form.querySelector('.error-summary').hidden=true;}
 function errors(names){clear();const summary=form.querySelector('.error-summary');summary.textContent=P('Перевірте дані у формі.','Check the form details.');for(const name of new Set(names)){const message=messages[name]||P('Перевірте це поле.','Check this field.'),p=form.querySelector('#e-'+name);if(p){p.textContent=message;p.hidden=false;}const el=name==='messenger'?q('messenger')[0]:q(name);el?.setAttribute?.('aria-invalid','true');el?.setAttribute?.('aria-describedby','e-'+name);}summary.hidden=false;summary.focus();}
 form.noValidate=true;form.onsubmit=async e=>{e.preventDefault();if(busy)return;const out=pending?pending.payload:data(),bad=[];if(!out.name||out.name.length>120)bad.push('name');if(!/^\+?[\d ()-]+$/.test(out.phone)||out.phone.replace(/\D/g,'').length<7||out.phone.replace(/\D/g,'').length>15)bad.push('phone');if(!['telegram','whatsapp','viber'].includes(out.messenger))bad.push('messenger');if(!validQ(out.quantity))bad.push('quantity');if(!out.consent)bad.push('consent');if(out.comment.length>2000)bad.push('comment');if(bad.length){errors(bad);return;}clear();busy=true;const submit=form.querySelector('[type=submit]'),label=submit.textContent,result=form.querySelector('.form-result');submit.disabled=true;submit.textContent=P('Надсилаємо…','Sending…');form.setAttribute('aria-busy','true');result.hidden=true;
 try{if(!pending){out.requestToken=token;pending={payload:out};await pendingStore.act('put',pending);lock();}const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending.payload),signal:AbortSignal.timeout(20000)}),value=await response.json();if(!response.ok||!value.ok){if(value.errors){pending=null;await pendingStore.act('delete');unlock();token=crypto.randomUUID();errors(Object.keys(value.errors));return;}throw Error(value.code||'request_failed');}const r=value.receipt;if(!r||!/^NFC-[A-F0-9]{20}$/.test(r.id||'')||!validV(r.variant)||!validQ(r.quantity)||!['custom','fixed','confirmed'].includes(r.quote?.status))throw Error('invalid_receipt');pending=null;await pendingStore.act('delete');safe.remove(draftKey);safe.set('nfc-v6-receipt',JSON.stringify(r));form.dataset.complete='true';result.replaceChildren();const heading=document.createElement('h2'),body=document.createElement('p'),reference=document.createElement('p'),link=document.createElement('a');heading.textContent=P('Дякуємо! Заявку отримано.','Thank you — we received your request.');body.textContent=r.mode==='local_test'?P('Заявку збережено в локальному перегляді. Повідомлення не надсилалися.','Your request was saved in the local preview. No messages were sent.'):P('Заявку збережено. Деталі замовлення погодимо у вибраному месенджері.','Your request is saved. We will agree the order details in your selected messenger.');reference.textContent=r.id;link.href=basePath+(uk?'/solutions':'/en/solutions');link.className='button secondary';link.textContent=P('Повернутися до карток','Back to cards');const hours=document.createElement('p'),telegram=document.createElement('a');hours.textContent=P('Зазвичай відповідаємо до 45 хвилин у робочий час: щодня 07:00–23:00.','We usually reply within 45 minutes during working hours: daily 07:00–23:00.');telegram.href='https://t.me/TijGabumG';telegram.target='_blank';telegram.rel='noopener noreferrer';telegram.className='text-action';telegram.textContent=P('Написати в Telegram','Message us on Telegram');result.append(heading,body,reference,hours,link,telegram);result.dataset.status='success';result.hidden=false;result.focus();submit.hidden=true;if(sticky)sticky.hidden=true;event('order_submit_success',{variant:r.variant,quantity:r.quantity});
 }catch(error){result.replaceChildren();const p=document.createElement('p'),retry=document.createElement('button');p.textContent=P('Не вдалося надіслати заявку. Дані збережено у формі — спробуйте ще раз або напишіть нам у месенджер.','We could not send your request. Your details remain in the form — retry or contact us in a messenger.');retry.type='button';retry.className='button secondary';retry.textContent=P('Спробувати ще раз','Try again');retry.onclick=()=>form.requestSubmit();result.append(p,retry);for(const[name,href]of [['Telegram','https://t.me/TijGabumG'],['WhatsApp','https://wa.me/380980421619'],['Viber','viber://chat?number=%2B380980421619']]){const a=document.createElement('a');a.href=href;a.textContent=name;a.className='text-action';result.append(a);}result.dataset.status='error';result.hidden=false;result.focus();event('order_submit_error');}finally{busy=false;submit.disabled=false;submit.textContent=label;form.removeAttribute('aria-busy');}};
 form.dataset.enhanced='true';
 /* NFC_FULLSTACK_END */
}
boot().catch(()=>{});
})();
