// NFC Instagram handoff v1 (SHA-256 recorded in refinement evidence), v18 truth.
// English for UA-only sections is a faithful translation. No new performance claims.
const pair=(uk,en)=>({uk,en});
export const instagram={
  id:'nfc-instagram-card', selection:'instagram', sku:'NFC-IG-READY', offer:'ready',
  name:'NFC Instagram Card', route:'/solutions/instagram-card', infoRoute:'/instagram-card',
  founderVideoEnabled:false,
  eyebrow:pair('ДЛЯ INSTAGRAM ВАШОГО БІЗНЕСУ','FOR YOUR BUSINESS INSTAGRAM'),
  headline:pair('Ваш Instagram — одним дотиком','Your Instagram — one tap away'),
  catalog:pair('Готова NFC-картка, що відкриває точний Instagram-профіль вашого бізнесу без пошуку, введення нікнейму та зайвих дій.','A ready-to-use NFC card that opens your business’s exact Instagram profile without searching, typing a username, or taking unnecessary steps.'),
  lead:pair('Клієнт торкається картки смартфоном і одразу відкриває точний Instagram-профіль вашого бізнесу — без пошуку та введення нікнейму.','A customer taps the card with a smartphone and opens your business’s exact Instagram profile — without searching or typing a username.'),
  mechanics:pair('Дотик → системне сповіщення → натискання на сповіщення → точний Instagram-профіль. Він відкривається в застосунку або браузері залежно від пристрою та налаштувань.','Tap → system notification → tap the notification → the exact Instagram profile. It opens in the app or browser depending on the device and settings.'),
  summary:pair('NFC Instagram Card працює за тим самим принципом, що й NFC Review Card: клієнт торкається картки смартфоном і натискає сповіщення. Відрізняються дизайн і призначення: замість форми Google-відгуку відкривається Instagram-профіль вашого бізнесу. Ми налаштовуємо картку на ваш профіль і передаємо готовою до використання.','NFC Instagram Card works the same way as NFC Review Card: the customer taps the card with a smartphone, then taps the notification. The design and purpose are different: it opens your business’s Instagram profile instead of a Google review form. We configure the card for your profile and deliver it ready to use.'),
  benefits:[pair('Прямий перехід у профіль','Direct profile access'),pair('10 × 10 см, товщина 3 мм','10 × 10 cm, 3 mm thick'),pair('Без обов’язкової щомісячної оплати','No mandatory monthly subscription')],
  honesty:pair('NFC Instagram Card не підписує клієнта автоматично й не гарантує певної кількості підписників. Вона прибирає пошук, введення нікнейму та зайві дії, щоб людині було простіше відкрити ваш профіль у потрібний момент.','NFC Instagram Card does not follow the account automatically and does not guarantee a specific number of followers. It removes searching, username entry, and unnecessary steps so the customer can open the profile more easily at the relevant moment.'),
  customerChoice:pair('Рішення підписатися, написати або переглянути контент завжди приймає сам клієнт.','The customer always decides whether to follow, message, or view your content.'),
  disclaimer:pair('NFC CARD — незалежний продукт, не є офіційним продуктом або партнером Instagram чи Meta.','NFC CARD is an independent product, not an official product or partner of Instagram or Meta.'),
  formIntro:pair('Залиште контактні дані та посилання на Instagram-профіль. Я зв’яжуся з вами, перевірю посилання й уточню деталі замовлення.','Leave your contact details and Instagram profile link. I will contact you, check the link and confirm your order details.'),
  crossHeading:pair('Потрібно не лише продовжити контакт, а й збирати Google-відгуки?','Do you also want to collect Google reviews?'),
  crossBody:pair('NFC Review Card відкриває форму відгуку конкретної Google-точки й допомагає зробити досвід задоволених клієнтів видимим для нових людей.','NFC Review Card opens the review form for a specific Google location and helps make satisfied customer experience visible to future customers.'),
  facts:[pair('100 × 100 мм · товщина 3 мм','100 × 100 mm · 3 mm thick'),pair('PVC · заокруглені кути','PVC · rounded corners'),pair('NFC · без QR-коду','NFC · no QR code'),pair('Лише готовий дизайн','Ready-made design only'),pair('Без обов’язкової щомісячної оплати','No mandatory monthly subscription')],
  commercialBenefits:[pair(['Точний профіль без пошуку','Людині не потрібно запам’ятовувати або вводити нікнейм.'],['The exact profile without search','The customer does not need to remember or type a username.']),pair(['Менше дій для клієнта','Дотик, сповіщення, перехід у профіль.'],['Fewer customer actions','Tap, notification, open the profile.']),pair(['Менше пояснень для персоналу','Адміністратору не потрібно щоразу диктувати нікнейм або допомагати з пошуком профілю. Достатньо показати картку — менше повторних пояснень і відволікань від записів, розрахунків та обслуговування.'],['Less explanation for staff','Staff do not need to spell out the username or help customers find the profile each time. They can simply point to the card, with fewer repeated explanations and interruptions to bookings, payments and customer service.']),pair(['Контакт може продовжитися','Клієнт може підписатися, переглянути контент, написати в Direct або поділитися профілем.'],['The connection can continue','Customers can follow, view content, send a direct message or share the profile.'])],
  includedItems:pair(['NFC Instagram Card із готовим дизайном','налаштування на точний Instagram-профіль','перевірка посилання перед відправленням','коротка інструкція з використання','підтримка після отримання','надійне пакування','безкоштовна доставка Новою поштою по Україні'],['NFC Instagram Card with the ready-made design','setup for the exact Instagram profile','link verification before shipping','short usage instructions','support after delivery','secure packaging','free Nova Poshta delivery within Ukraine']),
  specifications:pair(['Матеріал: PVC','Розмір: 100 × 100 мм','Товщина: 3 мм','Технологія: NFC','QR-код: немає','Персональний дизайн: немає','Обов’язкова щомісячна оплата: немає'],['Material: PVC','Size: 100 × 100 mm','Thickness: 3 mm','Technology: NFC','QR code: none','Custom design: unavailable','Mandatory monthly subscription: none']),
  placement:pair('На рецепції, касі, столику, стійці видачі, у шоурумі або в іншій точці, де клієнт завершує взаємодію з бізнесом.','At reception, checkout, a table, a pickup counter, a showroom, or another point where the customer finishes interacting with the business.'),
  payment:pair('Передоплата — 200 грн і входить у загальну вартість. Решта — після відправлення та отримання ТТН. Підготовка — орієнтовно до 5 робочих днів. Доставка Новою поштою по Україні безкоштовна.','The UAH 200 deposit is included in the total. The balance is due after dispatch and receipt of the tracking number. Preparation takes approximately up to 5 business days. Nova Poshta delivery within Ukraine is free.'),
  productSteps:[
    pair(['Ви надсилаєте точне посилання на Instagram.','Вкажіть Instagram-профіль вашого бізнесу у заявці.'],['You provide the exact Instagram profile link.','Include your business’s Instagram profile in the enquiry.']),
    pair(['Ми програмуємо й перевіряємо картку.','Перевіряємо перехід перед відправленням.'],['We program and verify the card.','We check the link before dispatch.']),
    pair(['Клієнт торкається картки смартфоном.','На екрані з’являється системне сповіщення.'],['The customer taps it with a smartphone.','A system notification appears.']),
    pair(['Клієнт натискає сповіщення — відкривається точний Instagram-профіль вашого бізнесу.','Після відкриття профілю клієнт сам обирає наступну дію.'],['The customer taps the notification and your exact Instagram profile opens.','After the profile opens, the customer chooses what to do next.'])
  ],
  productSEO:{title:pair('NFC Instagram Card — картка для переходу в Instagram | NFC CARD','NFC Instagram Card for Business | NFC CARD'),description:pair('NFC Instagram Card відкриває точний Instagram-профіль бізнесу одним дотиком. 100 × 100 мм, без QR-коду та обов’язкової щомісячної оплати.','Open your business’s exact Instagram profile with one NFC tap. Ready-made 10 × 10 cm card with no QR code or mandatory monthly subscription.')},
  infoSEO:{title:pair('Як перевести офлайн-клієнта в Instagram одним дотиком | NFC CARD','Connect In-Person Customers to Instagram with One Tap | NFC CARD'),description:pair('Допоможіть клієнтам швидко відкривати Instagram вашого бізнесу без пошуку та введення нікнейму. Як працює NFC Instagram Card.','Learn how NFC Instagram Card removes profile search and username entry, helping customers open your business Instagram more easily after a visit.')},
  info:{
    heading:pair('Не втрачайте контакт із клієнтом після візиту','Keep the connection after the customer’s visit'),
    lead:pair('Людина вже скористалася вашою послугою, зробила покупку або відвідала заклад. NFC Instagram Card дає їй найкоротший шлях до точного Instagram-профілю вашого бізнесу.','The customer has already used your service, made a purchase, or visited your location. NFC Instagram Card gives them the shortest route to your business’s exact Instagram profile.'),
    frictionHeading:pair('Клієнт уже поруч. Але ваш Instagram ще потрібно знайти.','The customer is already with you. Your Instagram still has to be found.'),
    friction:pair('Коли клієнти просять ваш Instagram, персоналу може доводитися щоразу повторювати нікнейм або показувати потрібний профіль. Якщо це повторюється протягом дня, такі пояснення відволікають від інших завдань. Картка прибирає саме цей повторюваний крок: адміністратор показує її, а клієнт відкриває профіль на власному телефоні.','When customers ask for your Instagram, staff may have to repeat the username or show them the right profile each time. If this happens throughout the day, those explanations interrupt other tasks. The card removes that repeated step: staff point to it, and the customer opens the profile on their own phone.'),
    stepsHeading:pair('Від офлайн-візиту до Instagram — одним дотиком','From an in-person visit to Instagram in one tap'),
    steps:[pair(['Картка знаходиться у зрозумілому місці.','На рецепції, касі, столику або стійці видачі.'],['Place the card within reach.','At reception, checkout, a table or a pickup counter.']),pair(['Клієнт торкається картки смартфоном.','На екрані з’являється системне сповіщення.'],['The customer taps with a smartphone.','A system notification appears on the screen.']),pair(['Клієнт натискає на сповіщення.','Відкривається точний Instagram-профіль. Людина сама вирішує, чи підписатися, написати або переглянути контент.'],['The customer taps the notification.','The exact Instagram profile opens. The customer decides whether to follow, message or view the content.'])],
    valueHeading:pair('Маленька дія, яка робить взаємодію з бізнесом простішою','A small action that makes the customer experience easier'),
    values:[pair(['Менше пошуку','Клієнту не потрібно вводити нікнейм і перевіряти, чи знайшов він правильний профіль.'],['Less searching','The customer does not need to type a username or check whether they found the right profile.']),pair(['Менше навантаження на персонал','Адміністратор показує картку замість того, щоб диктувати назву й допомагати з пошуком.'],['Less staff explanation','Staff show the card instead of spelling out a username and helping with search.']),pair(['Можливість продовжити контакт','Після візиту клієнт може бачити ваші нові роботи, товари, новини, пропозиції або написати в Direct.'],['An opportunity to continue the relationship','After the visit, customers can see your latest work, products, news and offers, or send a direct message.']),pair(['Використання реального потоку','Людина вже була у вашому бізнесі. Картка допомагає не втрачати цей момент через зайві цифрові кроки.'],['Better use of existing in-person traffic','The customer has already visited your business. The card helps keep that moment from being lost to unnecessary digital steps.'])],
    contexts:pair(['салон або barbershop','nail-, brow- чи lash-студія','косметологія, SPA або wellness','кафе, ресторан або кав’ярня','tattoo-студія','фітнес, yoga, Pilates або танці','шоурум чи спеціалізований магазин','автосалон, детейлінг або сервіс','готель, майстер-клас, подія чи творча студія'],['salon or barbershop','nail, brow or lash studio','beauty clinic, spa or wellness studio','café, restaurant or coffee shop','tattoo studio','fitness, yoga, Pilates or dance studio','showroom or specialist shop','car dealership, detailing or service centre','hotel, workshop, event or creative studio']),
    truthHeading:pair('Готова картка без складного запуску','A ready-to-use card without a complex setup'),
    truth:pair('Ви надсилаєте точне посилання на Instagram. Ми програмуємо картку, перевіряємо перехід і відправляємо її готовою до використання.','You send the exact Instagram link. We program the card, check the link and ship it ready to use.'),
    finalHeading:pair('Дайте клієнту найкоротший шлях до вашого Instagram','Give customers the shortest route to your Instagram'),
    finalBody:pair('Перегляньте NFC Instagram Card, ціну, характеристики та залиште заявку на налаштування під ваш профіль.','View NFC Instagram Card, its price and specifications, and enquire about setup for your profile.'),
    founderHeading:pair('Навіщо ми створили NFC Instagram Card','Why we created NFC Instagram Card'),
    founderBody:pair('Ми хочемо зробити просту взаємодію з бізнесом зручнішою: клієнту — швидко відкрити потрібний профіль, а персоналу — не пояснювати пошук щоразу. NFC Instagram Card прибирає зайві дії; підписатися, написати чи переглянути контент людина вирішує сама.','We want to make a simple interaction with a business more convenient: customers can open the right profile quickly, and staff do not have to explain the search each time. NFC Instagram Card removes unnecessary steps; customers decide whether to follow, message or view the content.'),
    comparisonBridge:pair('Принцип той самий — дотик смартфоном і перехід за налаштованим посиланням. Оберіть, яку дію ви хочете спростити: відкриття Instagram-профілю чи написання Google-відгуку.','The principle is the same: tap with a smartphone and open the configured link. Choose the action you want to make easier: opening your Instagram profile or writing a Google review.')
  }
};

const faq=(id,ukq,enq,uka,ena)=>({id,question:pair(ukq,enq),answer:pair(uka,ena)});
export const instagramGlobalFAQs=[
  faq('instagram-what','Що таке NFC Instagram Card?','What is NFC Instagram Card?','Це фізична NFC-картка, яка відкриває точний Instagram-профіль вашого бізнесу після дотику смартфоном.','It is a physical NFC card that opens your business’s exact Instagram profile after a smartphone tap.'),
  faq('instagram-follow','Чи підписує картка клієнта автоматично?','Does it follow the account automatically?','Ні. Вона лише відкриває профіль. Підписатися, написати або переглянути контент людина вирішує самостійно.','No. It only opens the profile. The customer decides whether to follow, message, or view the content.'),
  faq('instagram-review','Чим NFC Instagram Card відрізняється від NFC Review Card?','How is NFC Instagram Card different from NFC Review Card?','Спосіб використання однаковий: дотик смартфоном, сповіщення й перехід. Відрізняються дизайн і призначення: NFC Instagram Card відкриває Instagram-профіль, а NFC Review Card — форму Google-відгуку. Це окремі картки для різних дій.','They work the same way: a smartphone tap, a notification and a link. The design and purpose differ: NFC Instagram Card opens an Instagram profile, while NFC Review Card opens a Google review form. They are separate cards for different actions.')
];
export const instagramProductFAQs=[
  faq('app','Чи потрібен окремий застосунок?','Does it need a separate app?','Для самої картки окремий застосунок не потрібен. Профіль відкривається в Instagram або браузері — залежно від пристрою та його налаштувань.','The card itself does not need a separate app. The profile opens in Instagram or a browser depending on the device and its settings.'),
  faq('compatibility','Чи працює картка на iPhone та Android?','Does it work with iPhone and Android?','Картка працює із сучасними смартфонами, що підтримують NFC. На окремих Android-пристроях NFC потрібно ввімкнути в налаштуваннях.','The card works with modern NFC-enabled smartphones. On some Android devices, NFC must be enabled in settings.'),
  faq('rewrite','Чи можна змінити Instagram-профіль після покупки?','Can the Instagram profile be changed after purchase?','Так. Якщо посилання зміниться, картку можна перепрограмувати на новий профіль.','Yes. If the link changes, the card can be reprogrammed for the new profile.'),
  faq('qr','Чи є на картці QR-код?','Does the card have a QR code?','Ні. Ця версія NFC Instagram Card працює через NFC й не містить QR-коду.','No. This version of NFC Instagram Card works through NFC and has no QR code.'),
  faq('design','Чи можна замовити персональний дизайн?','Can I order a custom design?','Ні. NFC Instagram Card доступна лише у готовому дизайні.','No. NFC Instagram Card is available only in the ready-made design.'),
  faq('size','Який розмір картки?','What are the card dimensions?','100 × 100 мм, товщина — 3 мм.','100 × 100 mm and 3 mm thick.'),
  faq('price','Скільки коштує картка?','How much does the card cost?','Одна NFC Instagram Card коштує 1 500 грн, дві — 2 600 грн.','One NFC Instagram Card costs UAH 1,500; two cost UAH 2,600.'),
  faq('order','Як відбувається замовлення?','How do I order?','Ви залишаєте контактні дані, кількість і точне посилання на Instagram. Ми перевіряємо посилання, програмуємо картку й уточнюємо деталі доставки.','Leave your contact details, quantity and exact Instagram link. We check the link, program the card and confirm delivery details.'),
  faq('payment','Які умови оплати й доставки?','What are the payment and delivery terms?','Передоплата — 200 грн і входить у загальну вартість. Решта — після відправлення та отримання ТТН. Доставка Новою поштою по Україні безкоштовна.','The UAH 200 deposit is included in the total. The balance is due after dispatch and receipt of the tracking number. Nova Poshta delivery within Ukraine is free.')
];

export const instagramMedia={
 IG01:{id:'IG01',status:'approved',label:pair('Передня сторона біля вікна','Front view near a window'),asset:'instagram-card-real-front-window.webp',claimRole:'real_product_photo'},
 IG02:{id:'IG02',status:'approved',label:pair('Передня сторона над столом','Front view above a desk'),asset:'instagram-card-real-front-desk.webp',claimRole:'real_product_photo'},
 IG03:{id:'IG03',status:'approved',label:pair('Край і товщина','Edge and thickness'),asset:'instagram-card-real-edge-profile.webp',claimRole:'real_product_photo'},
 IG04:{id:'IG04',status:'approved',label:pair('Зворотний бік і кріплення','Back and mounting'),asset:'instagram-card-real-back-mounting.webp',claimRole:'real_product_photo'},
 IG05:{id:'IG05',status:'approved',label:pair('Промоілюстрація готового дизайну','Ready-design promotional illustration'),asset:'instagram-card-clean-front-render.webp',claimRole:'promotional_product_render'},
 IG07:{id:'IG07',status:'approved',label:pair('Передня сторона біля вікна','Front view near a window'),asset:'instagram-card-real-front-window.webp',claimRole:'real_product_photo'},
 IG08:{id:'IG08',status:'approved',label:pair('Край і товщина','Edge and thickness'),asset:'instagram-card-real-edge-profile.webp',claimRole:'real_product_photo'},
 IG09:{id:'IG09',status:'placeholder',label:pair('Профіль Instagram на смартфоні','Instagram profile on a smartphone'),asset:null,claimRole:'not_product_evidence'}
};
export function instagramPlaceholder(id,locale,esc,compact=false){
 const slot=instagramMedia[id];
 return `<div class="instagram-placeholder${compact?' compact':''}" data-placeholder="${id}" data-media-provenance="placeholder" data-media-claim-role="not_product_evidence"><span class="placeholder-category">NFC Instagram Card</span><strong>${esc(slot.label[locale])}</strong><span>${locale==='uk'?'Фото буде додано':'Photo coming soon'}</span></div>`;
}

export function instagramMediaEntry(id,asset){
 const slot=instagramMedia[id];
 if(!slot)throw Error('Unknown Instagram media slot');
 if(slot.status==='approved'&&slot.asset&&asset){
  const entry=asset(slot.asset);
  if(entry.status==='public'&&entry.product_id===instagram.id&&entry.provenance==='user_provided_business_asset'&&entry.claim_role===slot.claimRole)return entry;
 }
 return {media_type:'placeholder',alt_ua:slot.label.uk,alt_en:slot.label.en,
  caption_ua:'Місце для майбутнього фото: '+slot.label.uk+'. Фото буде додано.',
  caption_en:'Future photo placeholder: '+slot.label.en+'. Photo coming soon.'};
}
export function instagramMediaView(id,locale,esc,{asset,picture,cls='',eager=false,compact=false}={}){
 return instagramMediaEntry(id,asset).media_type==='placeholder'?instagramPlaceholder(id,locale,esc,compact):picture(instagramMedia[id].asset,cls,eager);
}
