import {copy} from './model.mjs';
import {instagram as ig, instagramProductFAQs, instagramMediaView} from './instagram.mjs';
export function instagramViews({locale,esc,url,finalCTA,asset,picture}){
 const t=p=>p[locale],P=(uk,en)=>locale==='uk'?uk:en;
 const list=items=>`<ul class="clean-list">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
 const facts=()=>list(ig.facts.map(t));
 const rows=(items,numbered=false)=>`<${numbered?'ol':'div'} class="${numbered?'steps':'meaning-rows'}">${items.map((item,i)=>{const [h,p]=t(item);return `<${numbered?'li':'div'}>${numbered?`<span class="step-number" aria-hidden="true">${i+1}</span>`:''}<h3>${esc(h)}</h3><p>${esc(p)}</p></${numbered?'li':'div'}>`}).join('')}</${numbered?'ol':'div'}>`;
 const faqs=()=>`<div class="faq-list">${instagramProductFAQs.map(f=>`<details><summary>${esc(t(f.question))}</summary><p>${esc(t(f.answer))}</p></details>`).join('')}</div>`;
 const productLink=(label,cls='button')=>`<a class="${cls}" href="${url(ig.route)}" data-event="catalog_product_open" data-product-id="${ig.id}">${label}</a>`;
 function details(){return `<div class="instagram-product-content product-details-body" id="product-details"><p class="detail-signature">${P('Одне торкання → Instagram-профіль.','One tap → Instagram profile.')}</p><section class="product-detail instagram-product-benefits"><p class="eyebrow">${P('ПЕРЕВАГИ','BENEFITS')}</p><h2>${P('Що стає простішим','What becomes easier')}</h2>${rows(ig.commercialBenefits)}</section><section class="product-detail instagram-product-steps"><p class="eyebrow">${P('ЯК ЦЕ ПРАЦЮЄ','HOW IT WORKS')}</p><h2>${P('Від посилання до готової картки','From your link to a ready-to-use card')}</h2>${rows(ig.productSteps,true)}<p>${esc(t(ig.customerChoice))}</p></section><section class="product-detail instagram-product-included"><h2>${P('Що входить','What is included')}</h2>${list(t(ig.includedItems))}</section><section class="product-detail instagram-product-specs"><h2>${P('Характеристики','Specifications')}</h2>${list(t(ig.specifications))}</section><section class="product-detail"><h2>${P('Де розмістити картку','Where to place the card')}</h2><p>${esc(t(ig.placement))}</p></section><section class="product-detail instagram-honesty"><h2>${P('Чесне уточнення','An honest clarification')}</h2><p>${esc(t(ig.honesty))}</p></section><section class="product-detail"><h2>${P('Оплата й доставка','Payment and delivery')}</h2><p>${esc(t(ig.payment))}</p><a href="${url('/delivery-and-payment')}" class="text-action">${P('Усі умови оплати й доставки','All payment and delivery terms')}</a></section><section class="product-detail"><h2>${esc(t(copy.support.heading))}</h2><p>${esc(t(copy.support.body))}</p><a class="text-action" href="${url('/warranty-and-returns')}">${P('Підтримка, гарантія й повернення','Support, warranty and returns')}</a></section><section class="product-detail instagram-product-faq"><h2>FAQ — NFC Instagram Card</h2>${faqs()}</section><p class="field-hint">${esc(t(ig.disclaimer))}</p><a class="button instagram-content-order" href="#request" data-order-entry data-variant="instagram" data-product-id="${ig.id}">${P('Замовити NFC Instagram Card','Order NFC Instagram Card')}</a></div>`;}
 function info(){
  const c=ig.info;
  return `<div class="instagram-info-content">
   <section class="section instagram-info-hero">
    <div><p class="eyebrow">${P('NFC-КАРТКА ДЛЯ INSTAGRAM','NFC CARD FOR INSTAGRAM')}</p><h1>${esc(t(c.heading))}</h1><p class="lede">${esc(t(c.lead))}</p><div class="instagram-actions">${productLink(P('Переглянути картку та ціну','View the card and price'))}<a class="text-action" href="#instagram-how">${P('Як це працює','How it works')}</a></div></div>
    ${instagramMediaView('IG07',locale,esc,{asset,picture,cls:'instagram-info-image',eager:true})}
   </section>
   <section class="section"><h2>${esc(t(c.frictionHeading))}</h2><p>${esc(t(c.friction))}</p></section>
   <section class="section" id="instagram-how" tabindex="-1"><h2>${esc(t(c.stepsHeading))}</h2>${rows(c.steps,true)}<p class="section-note">${esc(t(ig.mechanics))}</p></section>
   <section class="section"><h2>${esc(t(c.valueHeading))}</h2>${rows(c.values)}</section>
   <section class="section"><h2>${P('Де використовувати NFC Instagram Card','Where to use NFC Instagram Card')}</h2>${list(t(c.contexts))}</section>
   <section class="section instagram-info-truth"><div><h2>${esc(t(c.truthHeading))}</h2><p>${esc(t(c.truth))}</p>${facts()}<p>${esc(t(ig.honesty))}</p></div><div class="instagram-info-media-stack">${instagramMediaView('IG08',locale,esc,{asset,picture,cls:'instagram-info-image'})}${instagramMediaView('IG09',locale,esc,{asset,picture,compact:true})}</div></section>
   <section class="section instagram-founder-text"><h2>${esc(t(c.founderHeading))}</h2><p>${esc(t(c.founderBody))}</p></section>
   <section class="section"><h2>${P('Яку дію ви хочете спростити для клієнта?','Which action do you want to make easier for customers?')}</h2><p>${esc(t(c.comparisonBridge))}</p><div class="meaning-rows"><div><h3>${P('Відкрити Instagram','Open Instagram')}</h3><p>${P('Щоб клієнт міг підписатися, переглянути контент, написати або поділитися профілем.','So customers can follow, view content, send a message or share your profile.')}</p>${productLink(P('Замовити NFC Instagram Card','Order NFC Instagram Card'))}</div><div><h3>${P('Залишити Google-відгук','Leave a Google review')}</h3><p>${P('Щоб зробити досвід задоволених клієнтів публічним і посилювати довіру до бізнесу.','To make satisfied customers’ experiences public and help build trust in the business.')}</p><a href="${url('/solutions/review-card')}" class="button secondary" data-event="product_cross_sell_click" data-variant="standard">${P('Переглянути NFC Review Card','View NFC Review Card')}</a></div></div><p class="field-hint">${esc(t(ig.disclaimer))}</p></section>
   ${finalCTA({heading:t(c.finalHeading),body:t(c.finalBody),primaryLabel:P('Перейти до картки товару','Go to the product page'),primaryHref:url(ig.route),primaryEvent:'catalog_product_open'})}
  </div>`;
 }
 return {details,info};
}
