import uk from './niche-content.uk.json' with {type:'json'};
import en from './niche-content.en.json' with {type:'json'};
import pl from './niche-content.pl.json' with {type:'json'};
import {canonicalQuote, priceText} from './display.mjs';
import {galleryView} from './gallery-view.mjs';

export const nicheContent = Object.freeze({uk,en,pl});
export const nicheRoutes = Object.freeze({beauty:'/solutions/beauty-review-card',restaurant:'/solutions/restaurant-review-card'});
export const nicheMedia = Object.freeze({
  beauty:['beauty-review-card-front-hand.webp','beauty-review-card-group-hand.webp','beauty-review-card-group-front.webp','beauty-review-card-edge-thickness.webp','beauty-review-card-back-mounting.webp'],
  restaurant:['restaurant-review-card-front-hand.webp','restaurant-review-card-group-hand.webp','restaurant-review-card-group-front.webp','restaurant-review-card-edge-thickness.webp','restaurant-review-card-back-mounting.webp']
});

export function nicheViews({locale,esc,url,picture,asset}) {
  const data=nicheContent[locale];
  if(!data)throw Error('Unsupported niche locale');
  const shared=data.shared;
  const label={uk:{cards:'Картки',view:'Переглянути',one:'1 картка',two:'2 картки',more:'3+ картки',quote:'Індивідуальний розрахунок',back:'NFC CARD'},en:{cards:'Cards',view:'View',one:'1 card',two:'2 cards',more:'3+ cards',quote:'Individual quote',back:'NFC CARD'},pl:{cards:'Karty',view:'Zobacz',one:'1 karta',two:'2 karty',more:'Od 3 kart',quote:'Wycena indywidualna',back:'NFC CARD'}}[locale];
  const price=q=>priceText(canonicalQuote('branded',q,locale),locale);
  const link=(route,text,cls='text-action')=>`<a href="${esc(url(route))}" class="${cls}">${esc(text)}</a>`;
  function card(kind){
    const product=data.products[kind],route=nicheRoutes[kind],image=nicheMedia[kind][0];
    return `<article class="commerce-card niche-card" data-solution="${kind}-review-card"><div class="commerce-card-media">${picture(image,'catalog-product-image')}</div><div class="commerce-card-copy"><p class="eyebrow">${esc(product.eyebrow)}</p><h2>${link(route,product.name,'commerce-card-link')}</h2><p>${esc(product.catalog_description)}</p><ul class="clean-list">${product.catalog_benefits.map(value=>`<li>${esc(value)}</li>`).join('')}</ul><dl class="commerce-card-prices"><div><dt>${label.one}</dt><dd>${esc(price('1'))}</dd></div><div><dt>${label.two}</dt><dd>${esc(price('2'))}</dd></div></dl><p>${esc(shared.delivery_short)}</p>${link(route,product.cta_primary,'button')}</div></article>`;
  }
  function form(kind){
    const product=data.products[kind],fields=shared.form_labels,route=nicheRoutes[kind],solution=kind+'-review-card';
    const policyName={uk:'Політикою конфіденційності',en:'Privacy Policy',pl:'Politykę prywatności'}[locale];
    const policyAt=fields.consent.indexOf(policyName);
    if(policyAt<0)throw Error('Niche consent policy text is missing');
    const consentHTML=esc(fields.consent.slice(0,policyAt))+link('/privacy',policyName)+esc(fields.consent.slice(policyAt+policyName.length));
    const options=fields.quantity_options.map((text,index)=>`<option value="${['1','2','more','advice'][index]}">${esc(text)}</option>`).join('');
    const messengerOptions=(locale==='pl'?['whatsapp','telegram','viber']:['telegram','whatsapp','viber']).map(value=>`<label class="messenger-option"><input type="radio" name="messenger" value="${value}" required><span>${value==='whatsapp'?'WhatsApp':value==='telegram'?'Telegram':'Viber'}</span></label>`).join('');
    return `<section id="request" tabindex="-1" class="section request-section niche-request"><div class="request-intro"><p class="eyebrow">${esc(product.name)}</p><h2>${esc(product.form_heading)}</h2><p>${esc(product.form_intro)}</p><p>${esc(fields.materials_hint)}</p></div><form class="lead-form commerce-form" data-niche-form data-solution="${solution}" data-success-heading="${esc(product.form_success_heading)}" data-success-body="${esc(product.form_success_body)}" action="/api/leads" method="post"><div class="preview-notice"></div><div class="form-grid"><div class="field"><label for="f-name">${esc(fields.name)} *</label><input id="f-name" name="name" required maxlength="100" autocomplete="name"></div><div class="field"><label for="f-phone">${esc(fields.phone)} *</label><input id="f-phone" name="phone" type="tel" required maxlength="50" autocomplete="tel" inputmode="tel"><p class="field-hint">${esc(fields.phone_help)}</p></div></div><fieldset class="messenger-field"><legend>${esc(fields.messenger)} *</legend><div class="messenger-options">${messengerOptions}</div></fieldset><input type="hidden" name="variant" value="branded"><input type="hidden" name="source" value="${esc(url(route))}"><div class="field field-quantity"><label for="f-quantity">${esc(fields.quantity)} *</label><select id="f-quantity" name="quantity" required>${options}</select><p class="field-hint">${esc(fields.quantity_help)}</p></div><p class="quote-summary" data-niche-price aria-live="polite">${esc(price('1'))}</p><p class="field-hint">${esc(fields.free_request_note)}</p><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="field consent-field"><label for="f-consent"><input id="f-consent" name="consent" type="checkbox" required><span>${consentHTML}</span></label></div><p class="pending-notice" role="status" hidden></p><button class="button submit-button" type="submit">${esc(product.form_submit)}</button><div class="form-result" tabindex="-1" aria-live="polite" hidden></div></form></section>`;
  }
  function page(kind){
    const product=data.products[kind],names=nicheMedia[kind],route=nicheRoutes[kind];
    const gallery=galleryView({variant:kind,names,title:product.name,locale,P:(uk,en)=>locale==='uk'?uk:locale==='en'?en:({"Мініатюри фото та відео":"Miniatury zdjęć i filmów","Показати":"Pokaż","зображення":"zdjęcie","із":"z","Попередній матеріал":"Poprzednie zdjęcie","Наступний матеріал":"Następne zdjęcie","Фото та відео. Стрілки — попередній або наступний матеріал; Enter — відкрити.":"Zdjęcia. Strzałki zmieniają zdjęcie; Enter otwiera podgląd.","Збільшити зображення":"Powiększ zdjęcie","Гортайте фото та відео":"Przeglądaj zdjęcia","Галерея":"Galeria","Перегляд фото та відео картки":"Podgląd zdjęć karty","Закрити переглядач":"Zamknij podgląd","Зведіть або розведіть пальці, щоб змінити масштаб; перетягніть збільшене фото":"Zmień skalę gestem i przesuń powiększone zdjęcie"}[uk]||en),esc,picture,asset,temporaryNote:shared.media_labels.physical_example});
    const sections=product.sections.map(section=>`<section class="niche-detail" id="${esc(section.id)}"><h2>${esc(section.heading)}</h2>${(section.paragraphs||[]).map(text=>`<p>${esc(text)}</p>`).join('')}${section.items?`<ul class="clean-list">${section.items.map(text=>`<li>${esc(text)}</li>`).join('')}</ul>`:''}</section>`).join('');
    const faq=product.faq.map(item=>`<details><summary>${esc(item.question)}</summary><p>${esc(item.answer)}</p></details>`).join('');
    return `<article class="niche-product" data-niche-page="${kind}-review-card"><section class="section commerce-product niche-hero"><nav class="breadcrumbs" aria-label="Breadcrumbs">${link('/',label.back)}<span>/</span>${link('/solutions',label.cards)}<span>/</span><span aria-current="page">${esc(product.name)}</span></nav><div class="commerce-product-layout">${gallery}<div class="commerce-purchase"><p class="eyebrow">${esc(product.eyebrow)}</p><h1>${esc(product.h1)}</h1><p class="niche-descriptor">${esc(product.descriptor)}</p><p class="product-promise">${esc(product.headline)}</p><p>${esc(product.lead)}</p><p class="commerce-price">${esc(price('1'))}</p><p>${esc(shared.delivery_short)}</p>${link(route+'/#request',product.cta_primary,'button')}${link(route+'/#request',product.cta_secondary,'text-action')}${link(route+'/#niche-details',product.details_label,'text-action')}<p class="field-hint">${esc(product.cta_note)}</p><p class="product-short">${esc(product.summary)}</p></div></div></section><div class="niche-content section" id="niche-details">${sections}</div><section class="section niche-proof"><h2>${esc(shared.proof_heading)}</h2><p>${esc(shared.proof_body)}</p><p class="field-hint">${esc(shared.proof_note)}</p></section><section class="section niche-pricing"><h2>${esc(shared.payment_heading)}</h2><dl class="price-rows"><div><dt>${label.one}</dt><dd>${esc(price('1'))}</dd></div><div><dt>${label.two}</dt><dd>${esc(price('2'))}</dd></div><div><dt>${label.more}</dt><dd>${label.quote}</dd></div></dl><p>${esc(shared.price_note)}</p><p>${esc(shared.payment_body)}</p><p>${esc(shared.other_markets)}</p></section><section class="section faq-section"><div><p class="eyebrow">FAQ</p><h2>${esc(product.name)} · FAQ</h2></div><div class="faq-list">${faq}</div></section><section class="section product-cross-link"><h2>${esc(product.cross_sell.heading)}</h2><p>${esc(product.cross_sell.body)}</p>${link(product.cross_sell.target,product.cross_sell.label)}</section><section class="section final-conversion"><div><h2>${esc(product.final_heading)}</h2><p>${esc(product.final_body)}</p></div>${link(route+'/#request',product.cta_primary,'button')}</section>${form(kind)}</article>`;
  }
  return {card,page,shared,data};
}
