import uk from './niche-content.uk.json' with {type:'json'};
import en from './niche-content.en.json' with {type:'json'};
import pl from './niche-content.pl.json' with {type:'json'};
import {miniQuote,MINI_PRODUCTS,MINI_QUANTITIES} from './mini-contract.mjs';
import {galleryView} from './gallery-view.mjs';

export const nicheContent=Object.freeze({uk,en,pl});
export const nicheRoutes=Object.freeze({beauty:'/solutions/beauty-review-card',brandedBeauty:'/solutions/branded-beauty-review-card',restaurant:'/solutions/restaurant-review-card',brandedRestaurant:'/solutions/branded-restaurant-review-card'});
export const nicheMedia=Object.freeze({
 beauty:['beauty-review-card-front-hand.webp','beauty-review-card-group-hand.webp','beauty-review-card-group-front.webp','beauty-review-card-edge-thickness.webp','beauty-review-card-back-mounting.webp'],
 restaurant:['restaurant-review-card-front-hand.webp','restaurant-review-card-group-hand.webp','restaurant-review-card-group-front.webp','restaurant-review-card-edge-thickness.webp','restaurant-review-card-back-mounting.webp']
});
export const nicheKinds=Object.freeze(Object.keys(nicheRoutes));
export const miniId=kind=>kind==='brandedBeauty'?'branded-beauty-review-card':kind==='brandedRestaurant'?'branded-restaurant-review-card':kind+'-review-card';
export const miniMediaKind=kind=>kind.toLowerCase().includes('beauty')?'beauty':'restaurant';
const words={
 uk:{one:'картка',many:'картки',quote:'Індивідуальний розрахунок',other:'Інша кількість',advice:'Потрібна порада щодо кількості',concepts:'Запитати безкоштовні 3–4 початкові концепції',quantity:'Кількість',custom:'Вкажіть кількість',style:'Стиль бренду / кольори',logo:'Логотип або опис файлу',brandLink:'Сайт або Instagram',split:'Як розділити тираж між погодженими дизайнами (необов’язково)',catalog:'Картки',details:'Деталі',physical:'Фізичне замовлення',request:'Тип запиту',deposit:'Передоплата 200 грн — один раз за підтверджене фізичне замовлення, входить у суму. За заявку зараз нічого платити не потрібно.',plDeposit:'',ready:'Дизайн на фото є готовим і не змінюється; налаштовуємо лише вашу Google-точку.',branded:'Надішліть логотип, сайт або Instagram та стиль бренду. Підготуємо 3–4 початкові концепції безкоштовно; ви оберете напрям, попросите правки та погодите фінальний макет до виробництва.',splitExample:'Можна розподілити тираж між кількома погодженими дизайнами: 10 карток = 5 + 5 у двох дизайнах, разом 5000 грн.',sent:'Заявка не є оплатою або підтвердженим фізичним замовленням.'},
 en:{one:'card',many:'cards',quote:'Individual quote',other:'Other quantity',advice:'I need quantity advice',concepts:'Ask for 3–4 free initial concepts',quantity:'Quantity',custom:'Enter quantity',style:'Brand style / colours',logo:'Logo or file description',brandLink:'Website or Instagram',split:'Split across approved designs (optional)',catalog:'Cards',details:'Details',physical:'Physical order',request:'Request type',deposit:'The UAH 200 deposit applies once to a confirmed physical order and is included in the total. Nothing is due for this enquiry.',plDeposit:'',ready:'The design shown in the photos is fixed; we configure the link to your exact Google review form.',branded:'Send your logo, website or Instagram and brand style. We prepare 3–4 initial concepts free of charge. You choose a direction, request edits and approve the final artwork before production.',splitExample:'You may split one order across approved designs: 10 cards = 5 + 5 in two designs, UAH 5,000 total.',sent:'An enquiry is not payment or a confirmed physical order.'},
 pl:{one:'karta',many:'karty',quote:'Wycena indywidualna',other:'Inna liczba kart',advice:'Potrzebuję porady co do liczby kart',concepts:'Poproś o 3–4 bezpłatne wstępne projekty',quantity:'Liczba kart',custom:'Podaj liczbę kart',style:'Styl marki / kolory',logo:'Logo lub opis pliku',brandLink:'Strona internetowa lub Instagram',split:'Podział między zaakceptowane projekty (opcjonalnie)',catalog:'Karty',details:'Szczegóły',physical:'Zamówienie kart',request:'Rodzaj zapytania',deposit:'Zaliczka 20 PLN dotyczy dopiero potwierdzonego zamówienia po uzgodnieniu ceny i jest wliczona w sumę. Za zapytanie teraz nic nie płacisz.',ready:'Wzór widoczny na zdjęciach jest gotowy i nie jest zmieniany; konfigurujemy link do formularza opinii Twojej wizytówki Google.',branded:'Prześlij logo, link do strony lub Instagrama oraz styl marki. Bezpłatnie przygotujemy 3–4 wstępne warianty projektu. Wybierzesz kierunek, zgłosisz poprawki i zaakceptujesz finalny projekt przed produkcją.',splitExample:'Możesz podzielić jedno zamówienie między kilka zaakceptowanych projektów. Na przykład 10 kart może mieć podział 5 + 5 na dwa projekty; cenę ustalimy indywidualnie.',sent:'Zapytanie nie jest płatnością ani potwierdzonym zamówieniem.'}
};

export function nicheViews({locale,esc,url,picture,asset}){
 const data=nicheContent[locale], w=words[locale];if(!data||!w)throw Error('Unsupported niche locale');
 const link=(route,text,cls='text-action')=>`<a href="${esc(url(route))}" class="${cls}">${esc(text)}</a>`;
 const count=n=>locale==='uk'?`${n} ${n===1?'картка':n===2||n===4?'картки':'карток'}`:locale==='pl'?`${n} ${n===1?'karta':n===2||n===4?'karty':'kart'}`:`${n} ${n===1?'card':'cards'}`;
 const qtext=(kind,n)=>{const quote=miniQuote(miniId(kind),n,locale);return quote.amount===null?w.quote:locale==='uk'?`${quote.unitPrice} грн/шт. · ${quote.amount} грн`: `UAH ${quote.unitPrice} each · UAH ${quote.amount} total`;};
 const rows=kind=>locale==='pl'?`<div><dt>${w.quantity}</dt><dd>${w.quote}</dd></div>`:MINI_QUANTITIES.map(n=>`<div><dt>${count(n)}</dt><dd>${esc(qtext(kind,n))}</dd></div>`).join('')+`<div><dt>${w.other}</dt><dd>${w.quote}</dd></div>`;
 const concept=()=>`<div class="branded-concept niche-concept" data-design-role="custom_layout_example"><img src="/assets/media/v9/nfc-card-mark.svg" alt="" width="128" height="128"><span>${locale==='uk'?'Ваш логотип.<br>Ваші кольори.<br>Ваш дизайн.':locale==='en'?'Your logo.<br>Your colours.<br>Your design.':'Twoje logo.<br>Twoje kolory.<br>Twój projekt.'}</span><small>${locale==='uk'?'Приклад розміщення, не фото готової картки':locale==='en'?'Layout example, not a finished card photo':'Przykład układu, nie zdjęcie gotowej karty'}</small></div>`;
 function card(kind){
  const p=data.products[kind],route=nicheRoutes[kind],branded=MINI_PRODUCTS[miniId(kind)].designMode==='branded';
  return `<article class="commerce-card niche-card" data-solution="${miniId(kind)}"><div class="commerce-card-media">${branded?concept():picture(nicheMedia[miniMediaKind(kind)][0],'catalog-product-image')}</div><div class="commerce-card-copy"><p class="eyebrow">${esc(p.eyebrow)}</p><h2>${link(route,p.name,'commerce-card-link')}</h2><p>${esc(p.catalog_description)}</p><ul class="clean-list">${p.catalog_benefits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><dl class="commerce-card-prices">${locale==='pl'?rows(kind):[1,2].map(n=>`<div><dt>${count(n)}</dt><dd>${esc(qtext(kind,n))}</dd></div>`).join('')}</dl>${link(route,p.cta_primary,'button')}</div></article>`;
 }
 function form(kind){
  const p=data.products[kind],fields=data.shared.form_labels,route=nicheRoutes[kind],solution=miniId(kind),branded=MINI_PRODUCTS[solution].designMode==='branded';
  const policy={uk:'Політикою конфіденційності',en:'Privacy Policy',pl:'Politykę prywatności'}[locale],at=fields.consent.indexOf(policy);
  if(at<0)throw Error('Missing privacy link text');
  const consent=esc(fields.consent.slice(0,at))+link('/privacy',policy)+esc(fields.consent.slice(at+policy.length));
  const messenger=(locale==='pl'?['whatsapp','telegram','viber']:['telegram','whatsapp','viber']).map(v=>`<label class="messenger-option"><input type="radio" name="messenger" value="${v}" required><span>${v==='whatsapp'?'WhatsApp':v==='telegram'?'Telegram':'Viber'}</span></label>`).join('');
  const options=MINI_QUANTITIES.map(n=>`<option value="${n}">${count(n)}</option>`).join('')+`<option value="other">${w.other} — ${w.quote}</option><option value="advice">${w.advice}</option>`+(branded?`<option value="concepts">${w.concepts}</option>`:'');
  const brandFields=branded?`<div class="field"><label for="f-brand-link">${esc(w.brandLink)}</label><input id="f-brand-link" name="brandLink" maxlength="250" autocomplete="url"></div><div class="field"><label for="f-logo-note">${esc(w.logo)}</label><input id="f-logo-note" name="logoNote" maxlength="250"></div><div class="field"><label for="f-brand-style">${esc(w.style)}</label><input id="f-brand-style" name="brandStyle" maxlength="250"></div><div class="field"><label for="f-design-split">${esc(w.split)}</label><input id="f-design-split" name="designSplitNote" maxlength="250"></div>`:'';
  return `<section id="request" tabindex="-1" class="section request-section niche-request"><div class="request-intro"><p class="eyebrow">${esc(p.name)}</p><h2>${esc(p.form_heading)}</h2><p>${esc(p.form_intro)}</p><p>${esc(branded?w.branded:w.ready)}</p></div><form class="lead-form commerce-form" data-niche-form data-product-family="nfc-review-card-mini" data-solution="${solution}" data-design-mode="${branded?'branded':'ready'}" data-success-heading="${esc(p.form_success_heading)}" data-success-body="${esc(p.form_success_body)}" action="/api/leads" method="post"><div class="preview-notice"></div><div class="form-grid"><div class="field"><label for="f-name">${esc(fields.name)} *</label><input id="f-name" name="name" required maxlength="100" autocomplete="name"></div><div class="field"><label for="f-phone">${esc(fields.phone)} *</label><input id="f-phone" name="phone" type="tel" required maxlength="50" autocomplete="tel" inputmode="tel"><p class="field-hint">${esc(fields.phone_help)}</p></div></div><fieldset class="messenger-field"><legend>${esc(fields.messenger)} *</legend><div class="messenger-options">${messenger}</div></fieldset><input type="hidden" name="variant" value="${branded?'branded':'standard'}"><input type="hidden" name="source" value="${esc(url(route))}"><div class="field field-quantity"><label for="f-quantity">${esc(w.quantity)} *</label><select id="f-quantity" name="quantity" required>${options}</select></div><div class="field" data-custom-quantity hidden><label for="f-custom-quantity">${esc(w.custom)} *</label><input id="f-custom-quantity" name="customQuantity" type="number" min="1" max="10000" step="1" inputmode="numeric" disabled></div>${brandFields}<p class="quote-summary" data-niche-price aria-live="polite">${esc(qtext(kind,1))}</p><p class="field-hint">${esc(w.deposit)}</p><p class="field-hint">${esc(w.sent)}</p><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="field consent-field"><label for="f-consent"><input id="f-consent" name="consent" type="checkbox" required><span>${consent}</span></label></div><p class="pending-notice" role="status" hidden></p><button class="button submit-button" type="submit">${esc(p.form_submit)}</button><div class="form-result" tabindex="-1" aria-live="polite" hidden></div></form></section>`;
 }
 function page(kind){
  const p=data.products[kind],route=nicheRoutes[kind],branded=MINI_PRODUCTS[miniId(kind)].designMode==='branded';
  const gallery=galleryView({variant:branded?'branded-mini':kind,captionMode:branded?'physical-mini-example':undefined,names:nicheMedia[miniMediaKind(kind)],title:p.name,locale,P:(uk,en)=>locale==='uk'?uk:locale==='en'?en:({'Галерея':'Galeria'}[uk]||en),esc,picture,asset});
  const sections=p.sections.map(s=>`<section class="niche-detail" id="${esc(s.id)}"><h2>${esc(s.heading)}</h2>${(s.paragraphs||[]).map(x=>`<p>${esc(x)}</p>`).join('')}${s.items?`<ul class="clean-list">${s.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</section>`).join('');
  const faq=p.faq.map(x=>`<details><summary>${esc(x.question)}</summary><p>${esc(x.answer)}</p></details>`).join('');
  return `<article class="niche-product" data-niche-page="${miniId(kind)}"><section class="section commerce-product niche-hero"><nav class="breadcrumbs" aria-label="Breadcrumbs">${link('/','NFC CARD')}<span>/</span>${link('/solutions',w.catalog)}<span>/</span><span aria-current="page">${esc(p.name)}</span></nav><div class="commerce-product-layout">${gallery}<div class="commerce-purchase"><p class="eyebrow">${esc(p.eyebrow)}</p><h1>${esc(p.h1)}</h1><p class="niche-descriptor">${esc(p.descriptor)}</p><p class="product-promise">${esc(p.headline)}</p><p>${esc(p.lead)}</p><p class="commerce-price">${esc(qtext(kind,1))}</p><p>${esc(branded?w.branded:w.ready)}</p>${link(route+'/#request',p.cta_primary,'button')}${link(route+'/#niche-details',p.details_label,'text-action')}</div></div></section><div class="niche-content section" id="niche-details">${sections}</div>${branded?`<section class="section niche-proof"><h2>${esc(p.name)}</h2><p>${esc(w.branded)}</p><p>${esc(w.splitExample)}</p></section>`:''}<section class="section niche-pricing"><h2>${esc(data.shared.payment_heading)}</h2><dl class="price-rows">${rows(kind)}</dl><p>${esc(w.deposit)}</p><p>${esc(data.shared.other_markets)}</p></section><section class="section faq-section"><div><p class="eyebrow">FAQ</p><h2>${esc(p.name)} · FAQ</h2></div><div class="faq-list">${faq}</div></section><section class="section product-cross-link"><h2>${esc(p.cross_sell.heading)}</h2><p>${esc(p.cross_sell.body)}</p>${link(p.cross_sell.target,p.cross_sell.label)}</section><section class="section final-conversion"><div><h2>${esc(p.final_heading)}</h2><p>${esc(p.final_body)}</p></div>${link(route+'/#request',p.cta_primary,'button')}</section>${form(kind)}</article>`;
 }
 return {card,page,shared:data.shared,data};
}
