// Owner-confirmed seller and defect/refund policy, 2026-09-12.
// No address, registration number, legal status or unconfirmed guarantee is invented.
export function publicLegalPage(route, {locale, esc, link, url, contacts}) {
  const P = (uk, en) => locale === 'uk' ? uk : en;
  const seller = [P('Продавець і контакт', 'Seller and contact'), P('Продавець NFC CARD — Артем Антонов. Для питань щодо замовлення, повернення або персональних даних звертайтеся за контактами нижче.', 'NFC CARD is sold by Artem Antonov. For questions about orders, returns or personal data, use the contacts below.')];
  const returns = [P('Брак і повернення коштів', 'Defects and refunds'), P('Якщо картка має брак, приймаємо її повернення та повертаємо кошти. Зв’яжіться з нами: погодимо перевірку, повернення картки й повернення коштів. Перед оплатою погоджуємо інші умови повернення, зокрема для персоналізованої картки, та витрати на пересилання.', 'If a card is defective, we accept its return and refund your payment. Contact us to arrange the assessment, return and refund. Other return terms, including personalised cards and shipping costs, are agreed before payment.')];
  const privacy = route === '/privacy';
  const sections = privacy ? [seller,
    [P('Дані та мета обробки', 'Details and purpose'), P('Після вашої згоди та натискання кнопки надсилання обробляємо ім’я, телефон, обраний месенджер, картку або тип звернення, кількість, мову, сторінку форми й обмежені UTM-мітки переходу. Це потрібно, щоб відповісти на заявку та погодити замовлення. Коментар із форми не передається; додаткові деталі погоджуємо в месенджері. Згода на заявку не є згодою на маркетингові розсилки.', 'After your consent and submission, we process your name, phone, preferred messenger, card or enquiry type, quantity, language, form page and limited referral UTM tags. We use these details to reply and agree your order. The form comment is not transmitted; additional details are discussed in a messenger. Enquiry consent does not authorise marketing messages.')],
    [P('Зберігання та одержувачі', 'Storage and recipients'), P('Заявка спочатку зберігається у приватній базі PostgreSQL у Railway. Потім повідомлення з її даними надходить продавцю через Telegram. GitHub Pages розміщує сайт, Railway обробляє заявки, а Telegram доставляє повідомлення; ці платформи можуть обробляти дані за межами України. Збій Telegram не видаляє збережену заявку. Доступ до бази обмежений.', 'Your enquiry is first saved in a private PostgreSQL database on Railway. A notification containing the enquiry details is then delivered to the seller through Telegram. GitHub Pages hosts the site, Railway processes enquiries and Telegram delivers notifications; these platforms may process data outside Ukraine. A Telegram failure does not delete the saved enquiry. Database access is restricted.')],
    [P('Дані у браузері', 'Details in your browser'), P('Ім’я, контакти й коментар залишаються лише у відкритій формі до надсилання та не записуються застосунком у сховища браузера. У сесії зберігається тільки випадковий ідентифікатор спроби для захисту від дублікатів. Персональні дані форми не передаються в analytics.', 'Before submission, names, contacts and comments stay only in the open form and are not written to browser storage by the application. Only a random attempt identifier is retained for the session to prevent duplicates. Form personal data is not sent to analytics.')],
    [P('Доступ, виправлення та видалення', 'Access, correction and deletion'), P('Зберігаємо заявку, поки вона потрібна для відповіді, погодження й виконання замовлення та розгляду пов’язаних звернень. Для доступу, виправлення, видалення даних або відкликання згоди зверніться до Артема Антонова за контактами нижче, за можливості вкажіть номер заявки. Запити розглядає продавець; за потреби дані перевіряються перед зміною.', 'We retain the enquiry while it is needed to respond, agree and fulfil the order and handle related enquiries. To request access, correction, deletion or withdrawal of consent, contact Artem Antonov using the details below and include your enquiry reference if available. The seller handles these requests and may verify details before making changes.')]
  ] : route === '/terms' ? [seller,
    [P('Заявка та замовлення', 'Enquiry and order'), P('Заявка не є оплатою або автоматичним підтвердженням замовлення. До передоплати погоджуємо ціну, дизайн, строки та доставку. Перший макет Branded Review Card безкоштовний.', 'An enquiry is not payment or automatic order confirmation. Price, design, timing and delivery are agreed before the deposit. The first Branded Review Card mockup is free.')],
    [P('Ціна й оплата', 'Price and payment'), P('Ціни для України наведені в гривнях. Передоплата 200 грн входить у повну суму, залишок — після відправлення та номера ТТН. Для 3+ карток, Європи й інших країн погоджуємо індивідуальний розрахунок.', 'Ukraine prices are shown in UAH. The 200 UAH deposit is included in the total; the balance is paid after dispatch and the tracking number. For 3+ cards, Europe and other countries, we agree an individual quote.')], returns
  ] : [seller, returns,
    [P('Допомога з карткою', 'Card support'), P('Якщо перехід за NFC або посиланням працює некоректно, напишіть нам: допоможемо перевірити картку й налаштування. Строки та інші умови гарантії погоджуємо до оплати.', 'If the NFC interaction or destination link is not working correctly, contact us for help checking the card and setup. Warranty duration and other terms are agreed before payment.')]
  ];
  const title = privacy ? P('Політика конфіденційності', 'Privacy policy') : route === '/terms' ? P('Умови замовлення', 'Order terms') : P('Гарантія, повернення та допомога', 'Warranty, returns and help');
  return `<section class="section prose-page legal-page"><p class="eyebrow">NFC CARD</p><h1>${title}</h1>${sections.map(([h,p]) => `<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('')}${contacts()}${link(url('/contact'), P('Контакти', 'Contact'), 'button secondary')}</section>`;
}
