// Owner-confirmed seller and defect/refund policy, 2026-09-12.
// No address, registration number, legal status or unconfirmed guarantee is invented.
export function publicLegalPage(route, {locale, esc, link, url, contacts}) {
  const P = (uk, en) => locale === 'uk' ? uk : en;
  const seller = [P('Продавець і контакт', 'Seller and contact'), P('Продавець NFC CARD — Артем Антонов. Для питань щодо замовлення, повернення або персональних даних звертайтеся за контактами нижче.', 'NFC CARD is sold by Artem Antonov. For questions about orders, returns or personal data, use the contacts below.')];
  const returns = [P('Брак і повернення коштів', 'Defects and refunds'), P('Якщо картка має брак, приймаємо її повернення та повертаємо кошти. Зв’яжіться з нами: погодимо перевірку, повернення картки й повернення коштів. Перед оплатою погоджуємо інші умови повернення, зокрема для персоналізованої картки, та витрати на пересилання.', 'If a card is defective, we accept its return and refund your payment. Contact us to arrange the assessment, return and refund. Other return terms, including personalised cards and shipping costs, are agreed before payment.')];
  const privacy = route === '/privacy';
  const sections = privacy ? [seller,
    [P('Дані та мета обробки', 'Details and purpose'), P('Після вашої згоди та натискання кнопки надсилання обробляємо ім’я, телефон, обраний месенджер, картку або тип звернення, кількість, мову, сторінку форми й обмежені UTM-мітки переходу. Це потрібно, щоб відповісти на заявку та погодити замовлення. Коментар із форми Review Card або Branded Review Card не передається; додаткові деталі погоджуємо в месенджері. Для NFC Instagram Card також передаємо посилання на Instagram-профіль і необов’язковий коментар. Для NFC Review Card 3D передаємо цілу кількість карток, за наявності посилання на Google-точку та необов’язковий коментар. Згода на заявку не є згодою на маркетингові розсилки.', 'After your consent and submission, we process your name, phone, preferred messenger, card or enquiry type, quantity, language, form page and limited referral UTM tags. We use these details to reply and agree your order. The Review Card or Branded Review Card form comment is not transmitted; additional details are discussed in a messenger. For NFC Instagram Card, we also send the Instagram profile URL and optional comment. For NFC Review Card 3D, we send the whole-number quantity and, when provided, the Google location link and optional comment. Enquiry consent does not authorise marketing messages.')],
    [P('Дані заявки NFC Menu Card', 'NFC Menu Card enquiry details'), P('Для заявки NFC Menu Card також передаємо обрані виконання та кількості, статус онлайн-меню, а якщо меню вже є — його гостьове посилання. Необов’язковий коментар у цій формі теж передається. Для запиту лише на консультацію не передаємо кількість, виконання або ціну карток.', 'For an NFC Menu Card enquiry, we also transmit selected formats and quantities, online menu status and, when a menu exists, its guest-facing URL. An optional comment in this form is also transmitted. A consultation-only enquiry does not send card quantity, formats or a price.')],
    [P('Зберігання та одержувачі', 'Storage and recipients'), P('Заявка спочатку зберігається у приватній базі PostgreSQL у Railway. Потім повідомлення з її даними надходить продавцю через Telegram. GitHub Pages розміщує сайт, Railway обробляє заявки, а Telegram доставляє повідомлення; ці платформи можуть обробляти дані за межами України. Збій Telegram не видаляє збережену заявку. Доступ до бази обмежений.', 'Your enquiry is first saved in a private PostgreSQL database on Railway. A notification containing the enquiry details is then delivered to the seller through Telegram. GitHub Pages hosts the site, Railway processes enquiries and Telegram delivers notifications; these platforms may process data outside Ukraine. A Telegram failure does not delete the saved enquiry. Database access is restricted.')],
    [P('Дані у браузері', 'Details in your browser'), P('Ім’я, контакти й коментар залишаються лише у відкритій формі до надсилання та не записуються застосунком у сховища браузера. У сесії зберігаємо випадковий ідентифікатор спроби, її статус і номер підтвердженої заявки для захисту від дублікатів. Для Menu Card також зберігаємо обраний тип звернення, статус меню, виконання та кількість карток, щоб відновити налаштування форми. Ім’я, телефон, посилання на меню та коментар не записуємо в сховище браузера. Персональні дані форми не передаються в analytics.', 'Before submission, names, contacts and comments stay only in the open form and are not written to browser storage by the application. The session stores a random attempt identifier, its status and the confirmed enquiry reference to prevent duplicates. For Menu Card, it also stores enquiry type, menu status, selected formats and card quantities to restore the form configuration. Name, phone, menu URL and comment are not written to browser storage. Form personal data is not sent to analytics.')],
    [P('Доступ, виправлення та видалення', 'Access, correction and deletion'), P('Зберігаємо заявку, поки вона потрібна для відповіді, погодження й виконання замовлення та розгляду пов’язаних звернень. Для доступу, виправлення, видалення даних або відкликання згоди зверніться до Артема Антонова за контактами нижче, за можливості вкажіть номер заявки. Запити розглядає продавець; за потреби дані перевіряються перед зміною.', 'We retain the enquiry while it is needed to respond, agree and fulfil the order and handle related enquiries. To request access, correction, deletion or withdrawal of consent, contact Artem Antonov using the details below and include your enquiry reference if available. The seller handles these requests and may verify details before making changes.')]
  ] : route === '/terms' ? [seller,
    [P('Заявка та замовлення', 'Enquiry and order'), P('Заявка не є оплатою або автоматичним підтвердженням замовлення. До передоплати погоджуємо ціну, дизайн, строки та доставку. Перший макет Branded Review Card безкоштовний.', 'An enquiry is not payment or automatic order confirmation. Price, design, timing and delivery are agreed before the deposit. The first Branded Review Card mockup is free.')],
    [P('Ціна й оплата', 'Price and payment'), P('Ціни для України наведені в гривнях. Передоплата 200 грн за фізичне замовлення входить у повну суму, залишок — після відправлення та номера ТТН. Для NFC Menu Card діють опубліковані тарифи за сумарною кількістю карток цього товару: 1–4 — 1 000 грн/шт., 5–9 — 750, 10–24 — 600, від 25 — 500. Розробку онлайн-меню обговорюємо та оцінюємо окремо. Для 3+ Review Card і Branded Review Card, а також для Європи й інших країн погоджуємо індивідуальний розрахунок. Поточна пропозиція Instagram Card охоплює одну або дві картки. NFC Review Card 3D коштує 4 000 грн за кожну картку без пакетної знижки; передоплата 200 грн сплачується один раз за замовлення і входить у суму. Це прототип, який виготовляємо під замовлення; виконання та строк погоджуємо до передоплати.', 'Ukraine prices are shown in UAH. The UAH 200 deposit per physical order is included in the total; the balance is paid after dispatch and the tracking number. NFC Menu Card uses its published tiers based on the total number of Menu Cards: 1–4 at UAH 1,000 each, 5–9 at 750, 10–24 at 600 and 25+ at 500. Online menu development is discussed and quoted separately. For 3+ Review Card or Branded Review Card orders, and for Europe or other countries, we agree an individual quote. The current Instagram Card offer covers one or two cards. NFC Review Card 3D costs UAH 4,000 per card with no bundle discount; the UAH 200 deposit is paid once per order and is included in the total. This prototype is made to order; we agree its execution and production timeline before taking the deposit.')], returns
  ] : [seller, returns,
    [P('Допомога з карткою', 'Card support'), P('Якщо перехід за NFC або посиланням працює некоректно, напишіть нам: допоможемо перевірити картку й налаштування. Строки та інші умови гарантії погоджуємо до оплати.', 'If the NFC interaction or destination link is not working correctly, contact us for help checking the card and setup. Warranty duration and other terms are agreed before payment.')]
  ];
  const title = privacy ? P('Політика конфіденційності', 'Privacy policy') : route === '/terms' ? P('Умови замовлення', 'Order terms') : P('Гарантія, повернення та допомога', 'Warranty, returns and help');
  return `<section class="section prose-page legal-page"><p class="eyebrow">NFC CARD</p><h1>${title}</h1>${sections.map(([h,p]) => `<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('')}${contacts()}${link(url('/contact'), P('Контакти', 'Contact'), 'button secondary')}</section>`;
}
