// Owner-supplied Review 3D handoff copy; this is a fifth offer for Google reviews.
export const review3d = Object.freeze({
  id:'nfc-review-card-3d',
  route:'/solutions/review-card-3d',
  name:'NFC Review Card 3D',
  gallery:['review-card-3d-front-in-hand.webp','review-card-3d-front-on-desk.webp','review-card-3d-back.webp'],
  category:{uk:'3D-ДИЗАЙН · ОРГСКЛО',en:'3D DESIGN · ACRYLIC'},
  catalogHeadline:{uk:'Прозоре оргскло. Об’ємний дизайн. Прямий перехід до Google-відгуку.',en:'Clear acrylic. Dimensional design. A direct route to your Google review form.'},
  catalogBody:{uk:'Дизайнерська версія Review Card для рецепції та каси. Поєднує виразне 3D-оформлення зі звичною NFC-дією: клієнт підносить смартфон і відкриває форму відгуку вашого бізнесу.',en:'A design-focused Review Card for reception and checkout areas. It pairs dimensional styling with the familiar NFC action: a visitor brings their phone close to the card and opens your business’s review form.'},
  heroEyebrow:{uk:'ДИЗАЙНЕРСЬКА ВЕРСІЯ ДЛЯ GOOGLE-ВІДГУКІВ',en:'DESIGN-FOCUSED GOOGLE REVIEW CARD'},
  heroHeading:{uk:'Звичний дотик. Об’ємний дизайн.',en:'A familiar tap. A dimensional design.'},
  heroBody:{uk:'NFC-картка з оргскла для бізнесу, якому важливі і зручність клієнта, і вигляд деталей на рецепції. Прозорий край, глянцеві відблиски та об’ємне оформлення створюють виразний предмет у зоні обслуговування. А всередині — знайомий принцип Review Card: перехід до форми Google-відгуку вашої конкретної точки.',en:'An acrylic NFC card for businesses that care about both customer convenience and the details of their reception area. Its clear edge, glossy reflections and dimensional styling give a familiar review tool a distinctive physical form. The NFC function remains the same: opening the Google review form for your specific business location.'},
  fixedDesign:{uk:'Готове оформлення без зміни логотипа, кольорів чи написів. Посилання налаштовуємо на ваш бізнес.',en:'The fixed design is supplied as shown, without changes to the logo, colours or wording. We configure the link for your business.'},
  status:{uk:'Прототип · Доступний до замовлення · Виготовлення під замовлення',en:'Prototype · Available to order · Made to order'},
  heroNote:{uk:'Передоплата 200 грн входить у вартість. Доставка по Україні — за наш рахунок. Строк виготовлення погоджуємо до передоплати.',en:'The UAH 200 deposit is included in the total. Delivery within Ukraine is on us. We agree the production timeline before taking the deposit.'},
  sections:[
    {heading:{uk:'Для простору, де важливі деталі',en:'A considered detail for your reception area'},paragraphs:[
      {uk:'Ви підбираєте освітлення, оформлення рецепції та інші предмети, з якими зустрічається клієнт. Картка для відгуку теж може бути частиною цього простору, а не лише носієм посилання.',en:'You choose the lighting, reception finish and other objects your customers encounter. A review card can be part of that space, rather than just a carrier for a link.'},
      {uk:'NFC Review Card 3D створена для такого вибору: звична функція у виразнішому оформленні з оргскла. Її можна розмістити біля каси чи рецепції або показувати клієнтам після обслуговування.',en:'NFC Review Card 3D offers the familiar function in a more expressive acrylic design. Place it near reception or checkout, or show it to a customer after service.'}
    ]},
    {heading:{uk:'Дизайн, який має глибину',en:'Design with depth'},paragraphs:[
      {uk:'Прозорий край обрамлює композицію, об’ємні написи й символи додають їй рельєфу, а синьо-біла основа та кольорові деталі підтримують упізнаване оформлення Google-напрямку. На зображеннях можна роздивитися прототип спереду, під кутом і зі зворотного боку.',en:'The clear edge frames the composition, raised-looking lettering and symbols give the prototype its dimensional character, and the blue-and-white layout retains the familiar visual language of the Google-review range. The supplied images show the prototype from the front, at an angle and from the back.'},
      {uk:'Тут 3D — про оформлення фізичної картки. Не про окремий застосунок, екран чи складнішу дію для відвідувача.',en:'Here, 3D describes the physical design. It does not mean an additional app, a display or a more complicated interaction for the visitor.'}
    ]},
    {heading:{uk:'Та сама проста дія для клієнта',en:'The same simple customer action'},paragraphs:[
      {uk:'Після покупки або послуги працівник може запропонувати відвідувачу поділитися враженнями в Google. Клієнту не потрібно самостійно шукати назву бізнесу, правильну адресу та форму відгуку — потрібний перехід уже налаштований на картці.',en:'After a purchase or service, a member of staff can invite a customer to share their experience on Google. The card provides a configured route to the correct review form, rather than asking the customer to search for the business name, address and review option manually.'},
      {uk:'Працівник показує картку → клієнт підносить смартфон із підтримкою NFC → виконує запропонований телефоном перехід → відкриває форму відгуку конкретного бізнесу.',en:'Show the card → bring an NFC-compatible smartphone close → follow the phone’s prompt → open the review form for the correct business location.'},
      {uk:'Якщо телефон показав сповіщення, потрібно натиснути на нього. Google може попросити увійти в обліковий запис. Оцінку, текст і рішення опублікувати відгук відвідувач обирає сам.',en:'If a notification appears, the customer taps it. Google may ask them to sign in. The customer chooses the rating, wording and whether to submit the review.'},
      {uk:'Картка робить доступ до форми зручнішим. А опублікований досвід допомагає людям, які ще не були у вас, краще зрозуміти, чого очікувати від бізнесу.',en:'The card makes the form easier to reach. Published customer experiences can then help people who have not visited your business understand what to expect.'}
    ]},
    {heading:{uk:'Що ви отримуєте',en:'What is included'},paragraphs:[
      {uk:'Одну NFC Review Card 3D з оргскла у показаному готовому дизайні, налаштування переходу на форму відгуку вашої Google-точки та перевірку налаштованого посилання перед відправленням.',en:'One NFC Review Card 3D in the fixed acrylic design shown, configuration for your Google business location and a check of the configured link before dispatch.'},
      {uk:'Обов’язкової щомісячної оплати за використання картки немає. Для відкриття посилання відвідувачу не потрібен окремий застосунок NFC CARD.',en:'There is no mandatory monthly card subscription. Visitors do not need a separate NFC CARD app to open the link.'}
    ]},
    {heading:{uk:'Прототип, який можна замовити',en:'A prototype you can order'},paragraphs:[
      {uk:'На зображеннях показано прототип NFC Review Card 3D. Ця версія доступна до замовлення та виготовляється під замовлення — це не позначення складського залишку.',en:'The images show the NFC Review Card 3D prototype. Orders are accepted for made-to-order production; the prototype label does not mean that finished units are held in stock.'},
      {uk:'Перед виготовленням підтвердимо з вами конкретне виконання показаного дизайну, параметри виробу та строк готовності. Дизайн залишається готовим: персональне брендування для цієї версії не передбачене.',en:'Before production, we confirm the supplied execution of the pictured design, the physical specifications and the completion timeline. Custom branding is not offered for this version.'},
      {uk:'Потрібні ваш логотип і фірмові кольори? Для цього є окрема Branded Review Card.',en:'For your own logo and brand colours, choose the separate Branded Review Card.'}
    ]},
    {heading:{uk:'Як оформити замовлення',en:'Ordering, payment and delivery'},paragraphs:[
      {uk:'1. Залиште заявку. Вкажіть ім’я, контакт, зручний спосіб зв’язку та потрібну кількість карток. Додайте посилання на вашу Google-точку, якщо воно вже під рукою.',en:'Submit your name, contact, preferred contact method and quantity. Include your Google business-profile link if it is available.'},
      {uk:'2. Погодьте деталі. Уточнимо точний профіль бізнесу, параметри готового виробу, строк виготовлення та дані доставки.',en:'We then confirm the correct location, physical specifications, production timeline and delivery details. The UAH 200 deposit per order is part of the total. For one UAH 4,000 card, the remaining balance is UAH 3,800.'},
      {uk:'3. Внесіть передоплату. 200 грн за замовлення входять у загальну суму. Для однієї картки за 4 000 грн залишок становить 3 800 грн.',en:'We prepare and configure the card and ship it free via Nova Poshta within Ukraine. The balance is payable after dispatch and receipt of the tracking/waybill number, not automatically cash on delivery.'},
      {uk:'4. Отримайте підтвердження відправлення. Підготуємо й налаштуємо картку та відправимо Новою поштою по Україні за наш рахунок. Залишок сплачується після відправлення та отримання номера ТТН.',en:'Production and shipping are separate stages. The 3D production timeline is agreed for the order, not copied from another product.'},
      {uk:'Виготовлення і доставка — різні етапи. Строк готовності саме 3D-версії підтверджуємо під час погодження; він не підставляється автоматично зі строків інших товарів.',en:''}
    ]}
  ],
  faq:[
    [{uk:'Чим 3D-версія відрізняється від звичайної Review Card?',en:'What is different about the 3D version?'},{uk:'Оргсклом та об’ємним оформленням. Завдання залишається тим самим: відкрити форму Google-відгуку конкретного бізнесу. Вища ціна стосується виконання виробу, а не додаткових функцій Google.',en:'Its acrylic material and dimensional design. It opens the same Google review form. The price difference is for the physical execution, not additional Google functionality.'}],
    [{uk:'Чому ця картка коштує 4 000 грн?',en:'Why does it cost UAH 4,000?'},{uk:'Це окрема дизайнерська версія з оргскла та з об’ємним оформленням. Ви обираєте її за вигляд і виконання. Для тієї самої задачі у звичайному оформленні є Review Card; для власного логотипа й кольорів — Branded Review Card.',en:'It is a separate design-focused acrylic version. Standard Review Card serves the same purpose in a standard design; Branded Review Card offers a personalised logo-and-colour treatment.'}],
    [{uk:'Чи можна додати наш логотип або змінити кольори?',en:'Can you add our logo or change the colours?'},{uk:'Ні. NFC Review Card 3D замовляється лише в показаному готовому дизайні. Налаштування на вашу Google-точку входить у пропозицію, але не означає зміну оформлення. Для персонального дизайну оберіть Branded Review Card.',en:'No. This version uses the fixed design shown. Configuring the Google link does not change the artwork. For personalised artwork, choose Branded Review Card.'}],
    [{uk:'Прототип уже можна замовити?',en:'Can the prototype be ordered now?'},{uk:'Так, приймаємо замовлення на виготовлення цієї версії. Зображення демонструють прототип. До передоплати уточнюємо параметри виробу та погоджуємо строк готовності.',en:'Yes, orders are accepted for production. The images depict the prototype. We confirm specifications and the production timeline before taking a deposit.'}],
    [{uk:'Чи збирає вона більше відгуків, ніж інші картки?',en:'Does it collect more reviews than the other versions?'},{uk:'Вона відкриває ту саму форму відгуку. Ми не обіцяємо більше відгуків, вищих оцінок або кращої позиції в Google лише завдяки 3D-дизайну. Її відмінність — оформлення та матеріал.',en:'It opens the same review form. We do not promise additional reviews, higher ratings or a better Google position because of the 3D design.'}],
    [{uk:'Що потрібно для налаштування?',en:'What do you need for configuration?'},{uk:'Посилання на профіль саме тієї Google-точки, для якої замовляєте картку. Якщо є кілька філій, уточніть потрібну адресу. Логотип для цього готового дизайну надсилати не потрібно.',en:'The exact Google profile for the intended location. For multiple branches, specify the correct address. No logo is needed for this fixed design.'}],
    [{uk:'Як працює зі смартфоном?',en:'Which phones can use it?'},{uk:'Смартфон має підтримувати зчитування NFC-посилань. Клієнт підносить його до картки й виконує запропонований телефоном перехід; іноді потрібно натиснути сповіщення. Для відгуку Google може попросити увійти в акаунт. Сумісність конкретного телефона можна уточнити перед замовленням.',en:'A phone must support reading NFC links. Follow its prompt after bringing it close to the card. Google may require sign-in. Ask us about a specific phone before ordering.'}],
    [{uk:'Які умови оплати й доставки?',en:'What are the payment and delivery terms?'},{uk:'1 картка — 4 000 грн. Передоплата 200 грн за замовлення входить у загальну суму; залишок за одну картку — 3 800 грн після відправлення й отримання ТТН. Доставка Новою поштою по Україні безкоштовна. Обов’язкової щомісячної плати за картку немає.',en:'UAH 4,000 per card, with a UAH 200 deposit per order included in the total. The balance for one card is UAH 3,800 after dispatch and receipt of the waybill number. Nova Poshta delivery within Ukraine is free; there is no mandatory monthly card fee.'}],
    [{uk:'Чи можна замовити кілька карток?',en:'Can we order several cards?'},{uk:'Так, вкажіть потрібну кількість у заявці. Вартість однієї 3D-картки — 4 000 грн. Строк виготовлення потрібної кількості погодимо окремо. Пакетні ціни інших продуктів на 3D-версію не переносяться.',en:'Yes. Specify the quantity. Each 3D card is UAH 4,000; we agree the production timeline for that quantity. Bundle prices for other products do not apply to this version.'}]
  ],
  seo:{uk:['NFC Review Card 3D з оргскла — 4 000 грн | NFC CARD','NFC Review Card 3D з оргскла у готовому об’ємному дизайні. Перехід до Google-відгуку вашого бізнесу. 4 000 грн. Прототип під замовлення.'],en:['Acrylic NFC Review Card 3D — UAH 4,000 | NFC CARD','NFC Review Card 3D in a fixed dimensional acrylic design. Opens your Google business review form. UAH 4,000 per card. Prototype made to order.']}
});
